### ISSUE TITLE
Add sanitize_field_names to remote config

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-nodejs#1871] opened 2020-11-12 14:39 UTC
See elastic/apm#319 for details.

Note that the implementation of this also includes adding the option to [Kibana](https://github.com/elastic/kibana/blob/master/x-pack/plugins/apm/common/agent_configuration/setting_definitions/general_settings.ts).

**Comment by trentm** [comment] 2020-11-16 16:50
closing as a dupe of #1811

**Closed by trentm** 2020-11-16 16:50 UTC
Labels: [zube]: Backlog, agent-nodejs, cross APM agents
