### ISSUE TITLE
Group Instrumentations by Logical Name

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#2944] opened 2022-09-23 20:03 UTC
As the modules we instrument become more complex in their construction (more class based modules, more typescript compiled modules), we've found that there's often a need to do deep instrumentation of a specific file in a module.  i.e. it's no longer sufficient to instrument `redis`, we need to instrument `@redis/client/dist/lib/client`.

This presents some potential confusion around the `disableInstrumentations` key -- in order to disable an instrumentation multiple keys may need to be added to this data structure.

We should consider changes that would end-users to think of our instrumentations as logic entities rather than individual module files.  To quote from a separate discussion

> Users might *prefer* to have the disableInstrumentations key for this be "redis" rather than "@redis/client/...".

This would need some structural changes in instr/index.js for this (a richer `MODULES`).

**Comment by trentm** [comment] 2023-02-01 23:33
Dupe of #2992

**Closed by trentm** 2023-02-01 23:33 UTC
Labels: agent-nodejs
