### ISSUE TITLE
CI: Update CI to use New JSON Schemas

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#1867] opened 2020-11-10 16:23 UTC
The APM Server team is dropping [their use of JSON schemas](https://github.com/elastic/apm-server/pull/4393) in favor of in-code decoding logic.  Since JSON schemas as a valuable part of our development cycle, they'll still be generating schema docs for our CI to use.

Once https://github.com/elastic/apm-server/pull/4393 lands, we'll need to point our CI at these new schema files and make any other adjustments to CI in order to ensure we're validating against these new files. (this is the download script that we recently discovered wasn't working on Mac OS)

**Comment by trentm** [comment] 2020-11-16 17:19
```
[9:19:14 trentm@pink:~/el/apm-agent-nodejs (git:master)]
% node --require /Users/trentm/el/apm-agent-nodejs/test/_promise_rejection.js test/integration/api-schema/basic.js
processing /var/folders/kj/pd34mxx52575q85q6x13nmm40000gn/T/.schemacache/metadata.json...
processing /var/folders/kj/pd34mxx52575q85q6x13nmm40000gn/T/.schemacache/transactions/transaction.json...
processing /var/folders/kj/pd34mxx52575q85q6x13nmm40000gn/T/.schemacache/spans/span.json...
processing /var/folders/kj/pd34mxx52575q85q6x13nmm40000gn/T/.schemacache/errors/error.json...
/Users/trentm/el/apm-agent-nodejs/test/integration/api-schema/basic.js:20
  if (err) throw err
           ^

ResolverError: Error opening file "/var/folders/kj/pd34mxx52575q85q6x13nmm40000gn/T/.schemacache/metadata.json"
ENOENT: no such file or directory, open '/var/folders/kj/pd34mxx52575q85q6x13nmm40000gn/T/.schemacache/metadata.json'
    at ReadFileContext.fs.readFile [as callback] (/Users/trentm/el/apm-agent-nodejs/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/file.js:52:20)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:237:13)
```

This is failing now that https://github.com/elastic/apm-server/pull/4393 has landed.

**Comment by astorm** [comment] 2020-11-16 17:28
I think/hope this should be as simple as updating the `tar -x...` paths in https://github.com/elastic/apm-agent-nodejs/blob/master/test/integration/api-schema/download-json-schemas.sh

**Comment by trentm** [comment] 2020-11-16 18:21
Mostly that to start. Then we get some schema test failures. So far:

```
% node --require /Users/trentm/el/apm-agent-nodejs/test/_promise_rejection.js test/integration/api-schema/basic.js
processing /var/folders/kj/pd34mxx52575q85q6x13nmm40000gn/T/apm-schema-v2-cache/metadata.json...
processing /var/folders/kj/pd34mxx52575q85q6x13nmm40000gn/T/apm-schema-v2-cache/transaction.json...
processing /var/folders/kj/pd34mxx52575q85q6x13nmm40000gn/T/apm-schema-v2-cache/span.json...
processing /var/folders/kj/pd34mxx52575q85q6x13nmm40000gn/T/apm-schema-v2-cache/error.json...
TAP version 13
# metadata schema failure
ok 1 should be strictly equal
ok 2 should be strictly equal
ok 3 should be strictly equal
# transaction schema failure
ok 4 should be strictly equal
ok 5 should be strictly equal
ok 6 should be strictly equal
ok 7 should be strictly equal
ok 8 should be strictly equal
ok 9 should be strictly equal
ok 10 should be strictly equal
# span schema failure
ok 11 should be strictly equal
not ok 12 should be strictly equal
  ---
    operator: equal
    expected: 7
    actual:   6
    at: validateFieldMessages (/Users/trentm/el/apm-agent-nodejs/test/integration/api-schema/basic.js:203:5)
    stack: |-
      Error: should be strictly equal
          at Test.assert [as _assert] (/Users/trentm/el/apm-agent-nodejs/node_modules/tape/lib/test.js:260:54)
          at Test.bound [as _assert] (/Users/trentm/el/apm-agent-nodejs/node_modules/tape/lib/test.js:84:32)
          at Test.strictEqual (/Users/trentm/el/apm-agent-nodejs/node_modules/tape/lib/test.js:424:10)
          at Test.bound [as strictEqual] (/Users/trentm/el/apm-agent-nodejs/node_modules/tape/lib/test.js:84:32)
          at validateFieldMessages (/Users/trentm/el/apm-agent-nodejs/test/integration/api-schema/basic.js:203:5)
          at Test.<anonymous> (/Users/trentm/el/apm-agent-nodejs/test/integration/api-schema/basic.js:46:5)
          at Test.bound [as _cb] (/Users/trentm/el/apm-agent-nodejs/node_modules/tape/lib/test.js:84:32)
          at Test.run (/Users/trentm/el/apm-agent-nodejs/node_modules/tape/lib/test.js:101:31)
          at Test.bound [as run] (/Users/trentm/el/apm-agent-nodejs/node_modules/tape/lib/test.js:84:32)
          at Immediate.next [as _onImmediate] (/Users/trentm/el/apm-agent-nodejs/node_modules/tape/lib/results.js:85:19)
  ...
ok 13 should be strictly equal
ok 14 should be strictly equal
ok 15 should be strictly equal
ok 16 should be strictly equal
ok 17 should be strictly equal
ok 18 should be strictly equal
/Users/trentm/el/apm-agent-nodejs/test/integration/api-schema/basic.js:206
    t.strictEqual(field.message, expected.message)
                        ^

TypeError: Cannot read property 'message' of null
    at expectations.forEach.expected (/Users/trentm/el/apm-agent-nodejs/test/integration/api-schema/basic.js:206:25)
    at Array.forEach (<anonymous>)
    at validateFieldMessages (/Users/trentm/el/apm-agent-nodejs/test/integration/api-schema/basic.js:204:16)
    at Test.<anonymous> (/Users/trentm/el/apm-agent-nodejs/test/integration/api-schema/basic.js:46:5)
    at Test.bound [as _cb] (/Users/trentm/el/apm-agent-nodejs/node_modules/tape/lib/test.js:84:32)
    at Test.run (/Users/trentm/el/apm-agent-nodejs/node_modules/tape/lib/test.js:101:31)
    at Test.bound [as run] (/Users/trentm/el/apm-agent-nodejs/node_modules/tape/lib/test.js:84:32)
    at Immediate.next (/Users/trentm/el/apm-agent-nodejs/node_modules/tape/lib/results.js:85:19)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)

```

**Comment by trentm** [comment] 2020-11-16 21:57
The issue is this test:

```
  test('span schema failure', function (t) {
    t.strictEqual(validateSpan({}), false)
    validateFieldMessages(t, validateSpan.errors, [
      { field: 'data.duration', message: 'is required' },
      { field: 'data.name', message: 'is required' },
      { field: 'data.type', message: 'is required' },
      { field: 'data.id', message: 'is required' },
      { field: 'data.trace_id', message: 'is required' },
      { field: 'data.parent_id', message: 'is required' },
      { field: 'data', message: 'no schemas match' }
    ])
    t.end()
  })
```

With the new span.json schema, the "is-my-json-valid" validator will not identify that `{ field: 'data', message: 'no schemas match' }` error on an empty object:

```
> var validator = require('is-my-json-valid')
> var oldSpanSchema = require('/Users/trentm/el/apm-server/docs/spec/spans/span.json')
> var oldSpanValidator = validator(oldSpanSchema)
> newSpanValidator({})
false
> newSpanValidator.errors
[ { field: 'data.duration', message: 'is required' },
  { field: 'data.id', message: 'is required' },
  { field: 'data.name', message: 'is required' },
  { field: 'data.parent_id', message: 'is required' },
  { field: 'data.trace_id', message: 'is required' },
  { field: 'data.type', message: 'is required' } ]
```

only after other validation issues are resolved will it identify that validation issue:

```
> newSpanValidator({duration: 1, name: "foo", type: "my-type", id: 'foo', trace_id: 'foo', parent_id: 'foo'})
false
> newSpanValidator.errors
[ { field: 'data', message: 'no schemas match' } ]
```

I think it is a side-effect of the new generated v2 schemas using "anyOf" at the top-level:

```
{
  "type": "object",
  "properties": {...},
  "anyOf": [...]
}
```

whereas the old schema had a top-level "allOf":[...] that held that "anyOf" usage.

There is a different JSON validation package, ajv, that we can use that generates better validation error messages (more context), e.g.:

```
> newSpanValidator({})
false
> newSpanValidator.errors
[ { keyword: 'required',
    dataPath: '',
    schemaPath: '#/required',
    params: { missingProperty: 'duration' },
    message: 'should have required property \'duration\'' },
  { keyword: 'required',
    dataPath: '',
    schemaPath: '#/required',
    params: { missingProperty: 'id' },
    message: 'should have required property \'id\'' },
  { keyword: 'required',
    dataPath: '',
    schemaPath: '#/required',
    params: { missingProperty: 'name' },
    message: 'should have required property \'name\'' },
  { keyword: 'required',
    dataPath: '',
    schemaPath: '#/required',
    params: { missingProperty: 'parent_id' },
    message: 'should have required property \'parent_id\'' },
  { keyword: 'required',
    dataPath: '',
    schemaPath: '#/required',
    params: { missingProperty: 'trace_id' },
    message: 'should have required property \'trace_id\'' },
  { keyword: 'required',
    dataPath: '',
    schemaPath: '#/required',
    params: { missingProperty: 'type' },
    message: 'should have required property \'type\'' },
  { keyword: 'required',
    dataPath: '',
    schemaPath: '#/anyOf/0/required',
    params: { missingProperty: 'start' },
    message: 'should have required property \'start\'' },
  { keyword: 'required',
    dataPath: '',
    schemaPath: '#/anyOf/1/required',
    params: { missingProperty: 'timestamp' },
    message: 'should have required property \'timestamp\'' },
  { keyword: 'anyOf',
    dataPath: '',
    schemaPath: '#/anyOf',
    params: {},
    message: 'should match some schema in anyOf' } ]
```

Let's switch to ajv. 

Should it matter later, ajv also supports JSON Schema external references (`$ref`), so we'd not need a separate module (@apidevtools/json-schema-ref-parser) for that. It *doesn't* currently matter because the new v2 generated schema files no longer use refs.

**Closed** 2020-11-16 22:52 UTC
Labels: [zube]: Ready, agent-nodejs
