### ISSUE TITLE
SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332

### ISSUE THREAD

**Issue by gauravsunstone** [elastic/apm-agent-nodejs#3062] opened 2022-12-07 07:15 UTC
We have been using this package in our nodejs application from a while and everything was right
Suddenly from last 4 days we started facing this issue

`SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332`

Below is the configuration i am using to use apm

```
import apm from "elastic-apm-node"
apm.start({
    serviceName: "placement_apis",
    secretToken: "",
    serverUrl: "http://kibana.sunstone.in:8200",
    environment: process.env.NODE_ENV,
    captureBody: "all",
})
```

Not able to find any reason why this is happening when i am using http still getting this issue

**Comment by trentm** [comment] 2022-12-07 19:08
Hi @gauravsunstone,

Node.js will throw an error with that error message when attempting to use its `https` library to talk to an HTTP (rather than HTTPS) endpoint. From just the output you provided, I'm not sure if this error is when the APM agent is attempting to talk to the APM server at `http://kibana.sunstone.in:8200`, or if it is from some other HTTP client usage in your application.

Are you able to show trace logging output from the APM agent, by adding `logLevel: "trace"` to the `apm.start(...)` call, or by setting the `ELASTIC_APM_LOG_LEVEL=trace` environment variable?  If the issue is with the APM agent talking to APM server, then you would see log lines something like this:

```
...
{"log.level":"error","@timestamp":"2022-12-07T19:04:29.632Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"APM Server transport error: error fetching APM Server version: write EPROTO 4520830464:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
{"log.level":"error","@timestamp":"2022-12-07T19:04:29.632Z","log":{"logger":"elastic-apm-node"},"ecs":{"version":"1.6.0"},"message":"APM Server transport error (EPROTO): write EPROTO 4520830464:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
...
{"log.level":"trace","@timestamp":"2022-12-07T19:04:29.737Z","log":{"logger":"elastic-apm-node"},"event.module":"apmclient","reqId":"b9d1ce74a19aa3e89808555e54abb996","concluded":false,"ecs":{"version":"1.6.0"},"error":{"type":"Error","message":"write EPROTO 4520830464:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n","stack_trace":"Error: write EPROTO 4520830464:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n\n    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)\n    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)"},"message":"completePart intakeReq"}
...
```

The only way I would expect that to happen is if you had accidentally used "https://..." in your APM agent config, e.g. `serverUrl: "https://kibana.sunstone.in:8200"`.

(Aside: I would strongly suggest eventually making your APM server available via HTTPS and with some authentication.)

**Comment by gauravsunstone** [comment] 2022-12-08 05:53
The issue here is suddenly it started throwing the error after working fine for months
Also, my second issue of concern is that CPU usage got very high when i was getting this error
_I saw that in version 3.14 this issue was resolved but getting this issue on 3.40 of CPU usage high on down apm server_

When i restarted the apm server and elastic agent everything is back to normal without changing a single line in any configuration or code
If this was happening because of configuration issue HTTP or HTTPS issue this should not be working before this error and after the restart

Is there anything i can do to ensure why this is happening so that i can prevent it to happen again. Also, is there any way to impliment apm server in a way so that if that server is anytime down it should not effect the main application performance or CPU usage

**Comment by trentm** [comment] 2022-12-08 17:07
> Is there anything i can do to ensure why this is happening so that i can prevent it to happen again.

Without more details (e.g. more logs from the APM agent, possibly logs from APM server, the versions of APM server and Elastic Agent) it is hard to say. I don't really understand what happened here.

> Also, is there any way to impliment apm server in a way so that if that server is anytime down it should not effect the main application performance or CPU usage

Was the high CPU usage by *apm server*? or was it high CPU usage of your application due to the APM agent running in your application? If the latter, then it is possibly an issue with the APM agent.  Again, we would need some more details (and ideally a way to reproduce) to try to find the issue.

**Comment by gauravsunstone** [comment] 2022-12-16 09:02
@trentm 

So basically its a self hosted APM server
Please let me know if i can share some appropriate logs or data which will help community to understand the issue better

As fas as CPU issue is concerned, because of APM server downtime CPU of my application was high which i am pretty sure about because within few minutes i removed the APM implementation from my applications code and everything was seems to be normal

One more point APM server was also working fine by doing nothing but just restarting the machine

**Comment by trentm** [comment] 2022-12-16 17:39
Are you able to reproduce the high CPU usage?
Are you able to reproduce the "SSL routines:ssl3_get_record:wrong version number..." error message?
If yes to either of those, can you reproduce with "trace" level logging turned on for the APM agent (via `ELASTIC_APM_LOG_LEVEL=trace` or `logLevel: 'trace'` (https://www.elastic.co/guide/en/apm/agent/nodejs/current/troubleshooting.html#debug-mode)?  Those logs would help to isolate the issue. Thanks.

**Comment by gauravsunstone** [comment] 2022-12-20 05:35
As of now after restarting the processes there is no issues happening on the server
I will definitely keep in mind to share the trance level logs if this happens again
Till then if you can just let me know is there any limits on logs we can send to the APM server as after deep diving more i found there was a parallel process which runs continuously and generate huge amount of logs from which i have now removed the APM server

But still not sure if that can be the issue as i am not sure about usage limits of APM server

**Comment by trentm** [comment] 2022-12-21 00:46
@gauravsunstone I'm going to close this issue to keep it focused on the original issue.

> Till then if you can just let me know is there any limits on logs we can send to the APM server as after deep diving more i found there was a parallel process which runs continuously and generate huge amount of logs from which i have now removed the APM server

The Node.js APM agent doesn't currently support sending logs to APM server itself.  Are you using something like [Filebeat](https://www.elastic.co/guide/en/beats/filebeat/8.5/filebeat-overview.html) to send logs to Elasticsearch?  If this is an "overloading APM server" issue, then https://www.elastic.co/guide/en/apm/guide/current/troubleshoot-apm.html might be a good place to start.

**Closed by trentm** 2022-12-21 00:46 UTC
Labels: agent-nodejs, community
