### ISSUE TITLE
Add support for knex v0.18.0+

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1190] opened 2019-07-03 08:58 UTC

**Comment by christhegrand** [comment] 2020-01-03 18:35
Hi,
I noticed recently that when we upgraded our app to Knex 0.19.5 from Knex 0.16.3, we stopped getting information about the SQL queries that we are running in APM. For example, previously I would be able to see, when looking at a given transaction, separate spans showing "begin", "select * from user where user_id=123", "commit", etc., whereas now I am only seeing the "begin" and "commit" spans. Is this caused by the lack of support for Knex 0.18.0+ mentioned in this issue?

Thanks,
Chris

**Comment by sundarv85** [comment] 2020-03-26 16:05
Hello, Is there any support for Knex v0.20.11... We are also not seeing any data being captured

**Comment by lreuven** [comment] 2020-03-28 09:37
Hi Sundar,
thanks for the request, we've added it to our backlog and will give it a try in the near future.
fill free ton help & contribute.
Lior

**Comment by JCMais** [comment] 2020-05-07 13:02
I'm having the same issue than @christhegrand, is there anything we can do to make this issue move faster?

I'm available to work on this if necessary. I've started by updating the pg instrumentation to support pg >= 8: https://github.com/elastic/apm-agent-nodejs/pull/1735

**Comment by JCMais** [comment] 2020-07-28 13:39
The above issue was caused due to this https://github.com/elastic/apm-agent-nodejs/issues/873

It's fixed with the latest version of Node.js

I suppose this issue can be closed as v0.18.0+ is already supported

**Comment by Nisgrak** [comment] 2021-07-29 13:12
I'm having the same issue with knex 0.21.19.

I use node 14.17.0 and 3.18.0 of elastic-apm-node, load the data with `ELASTIC_APM_X=Y npm run start` this way:
```js
// main.ts
import elasticApmNode from "elastic-apm-node/start";

....
```

It's a NestJS + Mikro-ORM project and I try to set the asyncHooks to false, as say in other issues but the span for knex isn't show.

![image](https://user-images.githubusercontent.com/19597708/127497650-1ba768f5-c7fc-493a-b973-320651dbfacc.png)
![image](https://user-images.githubusercontent.com/19597708/127497679-2aa551eb-8269-4f7b-b6be-402d6777f194.png)
![image](https://user-images.githubusercontent.com/19597708/127497711-91babd49-67f1-4ab9-b379-2e884d1fe1c1.png)

**Comment by astorm** [comment] 2021-07-30 04:48
@Nisgrak can you provide an example query using knex code that reproduces the behavior you're describing?  That's usually the quickest way for us to figure out what's going on and why a span isn't being generated.

**Comment by Nisgrak** [comment] 2021-07-30 07:29
An example repository?

I execute a manual query in knex like this:
```js
async function findAll() {
	console.log("Test"); // This shows in the log above
	const test = this.repository.getKnex(); // Araw Knex instance

	return test.from("blacklist").select();
}
```

And the elastic log:
![image](https://user-images.githubusercontent.com/19597708/127617115-02962b1b-af67-482a-8a21-dd9d75993605.png)

**Comment by astorm** [comment] 2021-07-30 17:21
@Nisgrak A small-but-full program that reproduces the behavior you're seeing would be best.  Also (especially if it's not possible for you to share a small-but-full program) if you could share the version of  knex you're using, which database client driver (pg, mysql, etc.) you're using, and which version of the client driver that's at it'd be a big help.

Basically we want/need to be able to run a program and see the same "not generating a span" behavior you're seeing.  If we can do that, we can do some debugging, figure out the problem, and get a fix in.

Does that make sense?

**Comment by Nisgrak** [comment] 2021-08-01 16:14
@astorm The version of knex is 0.21.19.

I create a test repo https://github.com/Nisgrak/test-nest-mikroorm-apm, anything you need please ask 😄 

Thanks you!

**Comment by astorm** [comment] 2021-08-02 19:54
Thanks for the reproduction @Nisgrak -- looking things over it appears the code in https://github.com/Nisgrak/test-nest-mikroorm-apm uses the `@mikro-orm/sqlite` package to make its queries which, in turn, uses the `sqlite3` package to make its queries.

Our instrumentation of knex is (per [supported technology](https://www.elastic.co/guide/en/apm/agent/nodejs/master/supported-technologies.html)) to get better stack trace visualization.  The underlying DB queries still rely on our instrumentation of individual database packages.

The Node.js Agent doesn't currently instrument the `sqlite3` package.  This is why you're not seeing spans.  

Was `sqlite3` the only package where you weren't seeing spans, or were there other db-drivers where this happened?  If so, could you share which ones?

**Comment by Nisgrak** [comment] 2021-08-03 07:56
Hi @astorm,

In fact I'm using the `@mikro-orm/mariadb` package, which uses `mariadb` internally.
I switch to `@mikro-orm/mysql` (`mysql2` based) and now shows the spans...

If I make a PR to make `mariadb` compatible it would be accepted? I really need that compatibility.

Thanks for all your help!

**Closed** 2021-08-03 15:00 UTC
Labels: agent-nodejs, enhancement
