### ISSUE TITLE
Any plans to support websocket ?

### ISSUE THREAD

**Issue by Sonosar** [elastic/apm-agent-nodejs#143] opened 2017-12-25 19:17 UTC
Major part of our solution relies on websocket.
Just curious, are there plans to support websocket?

**Comment by watson** [comment] 2017-12-25 20:11
We don't currently have a way to get enough meta-data about WebSocket messages, as this depends largely on the content of the message. So we currently don't automatically start new transactions when a WebSocket message is detected.

Instead I suggest that you create a custom transaction when a new message is received by your server and end it again once you're done processing it. That will give you the same instrumentation capabilities as you'd get with a regular HTTP server.

You can read more about custom transactions in our docs: https://www.elastic.co/guide/en/apm/agent/nodejs/current/custom-transactions.html

Let me know how it goes. And if you have a good idea of how we can improve the experience for users of WebSockets out-of-the-box, I'd be happy to hear that as well 😃

**Comment by Qard** [comment] 2018-04-13 18:10
Closing as duplicate of #195.

**Closed by Qard** 2018-04-13 18:10 UTC
Labels: question
