### ISSUE TITLE
add support to node 16

### ISSUE THREAD

**Issue by sibelius** [elastic/apm-agent-nodejs#2053] opened 2021-04-21 12:00 UTC
**Is your feature request related to a problem? Please describe.**
node 16 is out

**Describe the solution you'd like**
add node 16 in the valid engines

**Describe alternatives you've considered**
only adding 16 at engines will solve this

**Additional context**

````
elastic-apm-node@3.12.1: The engine "node" is incompatible with this module. Expected version "^8.6.0 || 10 || 12 || 13 || 14". Got "16.0.0"
```

https://nodejs.medium.com/node-js-16-available-now-7f5099a97e70

**Comment by trentm** [comment] 2021-04-22 00:39
Closing as (now modified to include node v16) dupe of https://github.com/elastic/apm-agent-nodejs/issues/1840

**Closed by trentm** 2021-04-22 00:39 UTC
Labels: agent-nodejs
