### ISSUE TITLE
Investigate random Node core dump when running TAV tests on Jenkins CI

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#372] opened 2018-05-22 08:57 UTC
Lately our Jenkins CI have started to do random core dumps from time to time:

- https://apm-ci.elastic.co/job/elastic+apm-agent-nodejs+master+periodic-tav-tests/190/NODEJS_VERSION=8,TAV=knex+ws+graphql+express-graphql+elasticsearch+hapi+express,label=linux/console
- https://apm-ci.elastic.co/job/elastic+apm-agent-nodejs+master+periodic-tav-tests/188/NODEJS_VERSION=9,TAV=knex+ws+graphql+express-graphql+elasticsearch+hapi+express,label=linux/console
- https://apm-ci.elastic.co/job/elastic+apm-agent-nodejs+master+periodic-tav-tests/187/NODEJS_VERSION=8,TAV=ioredis+pg,label=linux/console

This have started happening after we upgraded [test-all-versions](https://github.com/watson/test-all-versions) from v3.3.2 to v3.3.3, so it might be related

**Comment by Qard** [comment] 2018-06-25 18:49
I've been unable to reproduce any core dumps so far, and all the links have expired at this point. Perhaps we should watch for future occurrences and record here what Node.js version and module + version it fails on exactly. Perhaps we can identify some pattern to it?

**Comment by watson** [comment] 2018-06-25 20:01
Good idea (didn't know they expired!). I have seen it a few times since, but it's not as frequent as before. I'll remember to update this issue with all the details

**Comment by alvarolobato** [comment] 2018-07-03 15:12
We can't reproduce this issue any longer, closing the issue and creating a new one if we find it again.

**Closed by alvarolobato** 2018-07-03 15:12 UTC
Labels: [zube]: Ready, ci

**Comment by watson** [comment] 2018-08-13 10:27
It [just happened again](https://apm-ci.elastic.co/job/elastic+apm-agent-nodejs+master+periodic-tav-tests/NODEJS_VERSION=9,TAV=generic-pool+mysql+mysql2+redis+koa-router+handlebars+mongodb-core,label=linux/275/console). So far only once, so I don't think we should spend time investigating unless it becomes a trend. But I'll save it here for prosperity:

<details>

```
01:13:01 Started by upstream project "elastic+apm-agent-nodejs+master+periodic-tav-tests" build number 275
01:13:01 originally caused by:
01:13:01  Started by timer
01:13:01 [EnvInject] - Loading node environment variables.
01:13:01 [EnvInject] - Preparing an environment for the build.
01:13:01 [EnvInject] - Keeping Jenkins system variables.
01:13:01 [EnvInject] - Keeping Jenkins build variables.
01:13:01 [EnvInject] - Injecting as environment variables the properties content 
01:13:01 HOME=$JENKINS_HOME
01:13:01 
01:13:01 [EnvInject] - Variables injected successfully.
01:13:01 [EnvInject] - Injecting contributions.
01:13:01 Building remotely on worker-064cef6e4cbffa6da (virtual x86_64 swarm ubuntu linux ubuntu-16.04 docker) in workspace /var/lib/jenkins/workspace/elastic+apm-agent-nodejs+master+periodic-tav-tests/NODEJS_VERSION/9/TAV/generic-pool+mysql+mysql2+redis+koa-router+handlebars+mongodb-core/label/linux
01:13:01 [WS-CLEANUP] Deleting project workspace...
01:13:01 [WS-CLEANUP] Done
01:13:01 Wiping out workspace first.
01:13:01 Cloning the remote Git repository
01:13:01 Cloning repository https://github.com/elastic/apm-agent-nodejs.git
01:13:01  > git init /var/lib/jenkins/workspace/elastic+apm-agent-nodejs+master+periodic-tav-tests/NODEJS_VERSION/9/TAV/generic-pool+mysql+mysql2+redis+koa-router+handlebars+mongodb-core/label/linux/src/github.com/elastic/apm-agent-nodejs # timeout=10
01:13:01 Using reference repository: /var/lib/jenkins/.git-references/apm-agent-nodejs.git
01:13:01 Fetching upstream changes from https://github.com/elastic/apm-agent-nodejs.git
01:13:01  > git --version # timeout=10
01:13:01 using GIT_SSH to set credentials master node jenkins user ~/.ssh
01:13:01  > git fetch --tags --progress https://github.com/elastic/apm-agent-nodejs.git +refs/heads/*:refs/remotes/origin/*
01:13:02  > git config remote.origin.url https://github.com/elastic/apm-agent-nodejs.git # timeout=10
01:13:02  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
01:13:02  > git config remote.origin.url https://github.com/elastic/apm-agent-nodejs.git # timeout=10
01:13:02 Fetching upstream changes from https://github.com/elastic/apm-agent-nodejs.git
01:13:02 using GIT_SSH to set credentials master node jenkins user ~/.ssh
01:13:02  > git fetch --tags --progress https://github.com/elastic/apm-agent-nodejs.git +refs/heads/*:refs/remotes/origin/*
01:13:02 Checking out Revision f341bd343741119c4ff7a757bf9ae57fc143569d (refs/remotes/origin/master)
01:13:02  > git config core.sparsecheckout # timeout=10
01:13:02  > git checkout -f f341bd343741119c4ff7a757bf9ae57fc143569d
01:13:02 Commit message: "feat(filters): filter set-cookie headers (#485)"
01:13:02  > git rev-list --no-walk f341bd343741119c4ff7a757bf9ae57fc143569d # timeout=10
01:13:02 [linux] $ /usr/local/bin/runbld /tmp/jenkins2305150345607795790.sh
01:13:02 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
01:13:07 runbld>>> runbld started
01:13:07 runbld>>> 1.5.16/a5d70b7708dffc5843803e429a69ee41be885719
01:13:10 runbld>>> Debug logging enabled.
01:13:10 runbld>>> BUILD: https://c150076387b5421f9154dfbf536e5c60.us-west1.gcp.cloud.es.io:9243/build-1463180427010/t/20180812011310-277AE0DB
01:13:12 runbld>>> Adding vcs info for the latest commit:  f341bd343741119c4ff7a757bf9ae57fc143569d
01:13:12 runbld>>> >>>>>>>>>>>> SCRIPT EXECUTION BEGIN >>>>>>>>>>>>
01:13:12 runbld>>> Adding /usr/lib/jvm/java-8-openjdk-amd64/bin to the path.
01:13:12 + ./test/script/docker/cleanup.sh
01:13:12 "docker stop" requires at least 1 argument.
01:13:12 See 'docker stop --help'.
01:13:12 
01:13:12 Usage:  docker stop [OPTIONS] CONTAINER [CONTAINER...]
01:13:12 
01:13:12 Stop one or more running containers
01:13:12 "docker rm" requires at least 1 argument.
01:13:12 See 'docker rm --help'.
01:13:12 
01:13:12 Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]
01:13:12 
01:13:12 Remove one or more containers
01:13:12 Total reclaimed space: 0B
01:13:12 + ./test/script/docker/run_tests.sh 9 generic-pool+mysql+mysql2+redis+koa-router+handlebars+mongodb-core
01:13:13 Sending build context to Docker daemon  483.3kB
01:13:13 
01:13:13 Step 1/5 : ARG NODE_VERSION
01:13:13  ---> 
01:13:13 Step 2/5 : FROM node:${NODE_VERSION}
01:13:14 9: Pulling from library/node
01:13:14 Digest: sha256:cddc729ef8326f7e8966c246ba2e87bad4c15365494ff3d681fa6f022cdab041
01:13:14 Status: Image is up to date for node:9
01:13:14  ---> 08a8c8089ab1
01:13:14 Step 3/5 : RUN apt-get update &&     apt-get install -y xsltproc libxml2-utils &&     rm -rf /var/lib/apt/lists/*
01:13:14  ---> Using cache
01:13:14  ---> 6ff281c97750
01:13:14 Step 4/5 : ENV NPM_CONFIG_PREFIX /home/node/.npm-global
01:13:14  ---> Using cache
01:13:14  ---> 5d566c1bae18
01:13:14 Step 5/5 : WORKDIR /app
01:13:14  ---> Using cache
01:13:14  ---> f5ed3caeb2c4
01:13:14 Successfully built f5ed3caeb2c4
01:13:14 Successfully tagged apm-agent-nodejs:node-9
01:13:16 Creating network "test_default" with the default driver
01:13:16 Creating volume "test_nodemysqldata" with local driver
01:13:16 Creating volume "test_nodemssqldata" with local driver
01:13:16 Creating volume "test_nodepgdata" with local driver
01:13:16 Creating volume "test_nodeesdata" with local driver
01:13:16 Creating volume "test_nodemongodata" with local driver
01:13:16 Creating volume "test_nodecassandradata" with local driver
01:13:16 Creating test_postgres_1 ... 
01:13:16 Creating test_mssql_1 ... 
01:13:16 Creating test_redis_1 ... 
01:13:16 Creating test_mysql_1 ... 
01:13:16 Creating test_cassandra_1 ... 
01:13:16 Creating test_elasticsearch_1 ... 
01:13:16 Creating test_mongodb_1 ... 
01:13:16 Creating test_postgres_1
01:13:16 Creating test_mssql_1
01:13:16 Creating test_redis_1
01:13:16 Creating test_mongodb_1
01:13:16 Creating test_cassandra_1
01:13:16 Creating test_mysql_1
01:13:16 Creating test_elasticsearch_1
01:13:17 
01:13:17 Creating test_postgres_1 ... done
01:13:17 
01:13:17 Creating test_mssql_1 ... done
01:13:17 
01:13:17 Creating test_redis_1 ... done
01:13:18 
01:13:18 Creating test_mongodb_1 ... done
01:13:19 
01:13:19 Creating test_cassandra_1 ... done
01:13:19 
01:13:19 Creating test_mysql_1 ... done
01:13:19 
01:13:19 Creating test_elasticsearch_1 ... done
01:15:07 
01:15:07 > dtrace-provider@0.8.7 install /app/node_modules/dtrace-provider
01:15:07 > node-gyp rebuild || node suppress-error.js
01:15:07 
01:15:08 make: Entering directory '/app/node_modules/dtrace-provider/build'
01:15:08   TOUCH Release/obj.target/DTraceProviderStub.stamp
01:15:08 make: Leaving directory '/app/node_modules/dtrace-provider/build'
01:15:09 
01:15:09 > https-pem@2.0.0 postinstall /app/node_modules/https-pem
01:15:09 > node install.js
01:15:09 
01:15:10 added 1137 packages in 107.011s
01:15:10 v9.11.2
01:15:11 5.6.0
01:15:11 
01:15:11 > elastic-apm-node@1.10.2 test-tav /app
01:15:11 > tav --quiet
01:15:11 
01:15:11 -- required packages ["handlebars@4.0.11"]
01:15:11 -- installing ["handlebars@4.0.11"]
01:15:19 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:15:19 -- required packages ["handlebars@4.0.10"]
01:15:19 -- installing ["handlebars@4.0.10"]
01:15:26 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:15:26 -- required packages ["handlebars@4.0.9"]
01:15:26 -- installing ["handlebars@4.0.9"]
01:15:34 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:15:34 -- required packages ["handlebars@4.0.8"]
01:15:34 -- installing ["handlebars@4.0.8"]
01:15:41 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:15:41 -- required packages ["handlebars@4.0.7"]
01:15:41 -- installing ["handlebars@4.0.7"]
01:15:48 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:15:49 -- required packages ["handlebars@4.0.6"]
01:15:49 -- installing ["handlebars@4.0.6"]
01:15:56 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:15:56 -- required packages ["handlebars@4.0.5"]
01:15:56 -- installing ["handlebars@4.0.5"]
01:16:04 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:16:04 -- required packages ["handlebars@4.0.4"]
01:16:04 -- installing ["handlebars@4.0.4"]
01:16:11 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:16:11 -- required packages ["handlebars@4.0.3"]
01:16:11 -- installing ["handlebars@4.0.3"]
01:16:17 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:16:18 -- required packages ["handlebars@4.0.2"]
01:16:18 -- installing ["handlebars@4.0.2"]
01:16:24 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:16:25 -- required packages ["handlebars@4.0.1"]
01:16:25 -- installing ["handlebars@4.0.1"]
01:16:31 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:16:32 -- required packages ["handlebars@4.0.0"]
01:16:32 -- installing ["handlebars@4.0.0"]
01:16:38 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:16:39 -- required packages ["handlebars@3.0.3"]
01:16:39 -- installing ["handlebars@3.0.3"]
01:16:45 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:16:45 -- required packages ["handlebars@3.0.2"]
01:16:45 -- installing ["handlebars@3.0.2"]
01:16:52 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:16:52 -- required packages ["handlebars@3.0.1"]
01:16:52 -- installing ["handlebars@3.0.1"]
01:16:59 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:16:59 -- required packages ["handlebars@3.0.0"]
01:16:59 -- installing ["handlebars@3.0.0"]
01:17:05 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:17:06 -- required packages ["handlebars@2.0.0"]
01:17:06 -- installing ["handlebars@2.0.0"]
01:17:12 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:17:12 -- required packages ["handlebars@1.3.0"]
01:17:12 -- installing ["handlebars@1.3.0"]
01:17:18 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:17:18 -- required packages ["handlebars@1.2.1"]
01:17:18 -- installing ["handlebars@1.2.1"]
01:17:24 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:17:25 -- required packages ["handlebars@1.2.0"]
01:17:25 -- installing ["handlebars@1.2.0"]
01:17:31 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:17:31 -- required packages ["handlebars@1.1.2"]
01:17:31 -- installing ["handlebars@1.1.2"]
01:17:37 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:17:38 -- required packages ["handlebars@1.1.1"]
01:17:38 -- installing ["handlebars@1.1.1"]
01:17:44 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:17:44 -- required packages ["handlebars@1.1.0"]
01:17:44 -- installing ["handlebars@1.1.0"]
01:17:50 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:17:50 -- required packages ["handlebars@1.0.12"]
01:17:50 -- installing ["handlebars@1.0.12"]
01:17:56 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:17:57 -- required packages ["handlebars@1.0.11"]
01:17:57 -- installing ["handlebars@1.0.11"]
01:18:03 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:18:03 -- required packages ["handlebars@1.0.10"]
01:18:03 -- installing ["handlebars@1.0.10"]
01:18:09 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:18:09 -- required packages ["handlebars@1.0.9"]
01:18:09 -- installing ["handlebars@1.0.9"]
01:18:15 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:18:15 -- required packages ["handlebars@1.0.8"]
01:18:15 -- installing ["handlebars@1.0.8"]
01:18:21 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:18:22 -- required packages ["handlebars@1.0.7"]
01:18:22 -- installing ["handlebars@1.0.7"]
01:18:27 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:18:28 -- required packages ["handlebars@1.0.6"]
01:18:28 -- installing ["handlebars@1.0.6"]
01:18:34 -- running test "node test/instrumentation/modules/handlebars.js" with handlebars
01:18:34 -- required packages ["koa@2","koa-router@7.4.0"]
01:18:34 -- installing ["koa@2","koa-router@7.4.0"]
01:18:42 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:18:42 -- required packages ["koa@2","koa-router@7.3.0"]
01:18:42 -- installing ["koa@2","koa-router@7.3.0"]
01:18:50 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:18:50 -- required packages ["koa@2","koa-router@7.2.1"]
01:18:50 -- installing ["koa@2","koa-router@7.2.1"]
01:18:58 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:18:58 -- required packages ["koa@2","koa-router@5.4.2"]
01:18:58 -- installing ["koa@2","koa-router@5.4.2"]
01:19:06 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:19:06 Sun, 12 Aug 2018 01:19:06 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at test/instrumentation/modules/koa-router/index.js:82:6
01:19:06 Sun, 12 Aug 2018 01:19:06 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at test/instrumentation/modules/koa-router/index.js:83:6
01:19:06 -- required packages ["koa@2","koa-router@7.2.0"]
01:19:06 -- installing ["koa@2","koa-router@7.2.0"]
01:19:14 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:19:14 -- required packages ["koa@2","koa-router@7.1.1"]
01:19:14 -- installing ["koa@2","koa-router@7.1.1"]
01:19:22 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:19:22 -- required packages ["koa@2","koa-router@5.4.1"]
01:19:22 -- installing ["koa@2","koa-router@5.4.1"]
01:19:30 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:19:30 Sun, 12 Aug 2018 01:19:30 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at test/instrumentation/modules/koa-router/index.js:82:6
01:19:30 Sun, 12 Aug 2018 01:19:30 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at test/instrumentation/modules/koa-router/index.js:83:6
01:19:30 -- required packages ["koa@2","koa-router@7.1.0"]
01:19:30 -- installing ["koa@2","koa-router@7.1.0"]
01:19:37 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:19:38 -- required packages ["koa@2","koa-router@5.4.0"]
01:19:38 -- installing ["koa@2","koa-router@5.4.0"]
01:19:45 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:19:45 Sun, 12 Aug 2018 01:19:45 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at test/instrumentation/modules/koa-router/index.js:82:6
01:19:45 Sun, 12 Aug 2018 01:19:45 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at test/instrumentation/modules/koa-router/index.js:83:6
01:19:45 -- required packages ["koa@2","koa-router@7.0.1"]
01:19:45 -- installing ["koa@2","koa-router@7.0.1"]
01:19:53 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:19:53 -- required packages ["koa@2","koa-router@5.3.0"]
01:19:53 -- installing ["koa@2","koa-router@5.3.0"]
01:20:00 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:20:01 Sun, 12 Aug 2018 01:20:01 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at test/instrumentation/modules/koa-router/index.js:82:6
01:20:01 Sun, 12 Aug 2018 01:20:01 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at test/instrumentation/modules/koa-router/index.js:83:6
01:20:01 -- required packages ["koa@2","koa-router@7.0.0"]
01:20:01 -- installing ["koa@2","koa-router@7.0.0"]
01:20:08 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:20:08 -- required packages ["koa@2","koa-router@6.2.0"]
01:20:08 -- installing ["koa@2","koa-router@6.2.0"]
01:20:15 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:20:16 -- required packages ["koa@2","koa-router@6.1.0"]
01:20:16 -- installing ["koa@2","koa-router@6.1.0"]
01:20:23 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:20:24 -- required packages ["koa@2","koa-router@6.0.1"]
01:20:24 -- installing ["koa@2","koa-router@6.0.1"]
01:20:31 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:20:31 -- required packages ["koa@2","koa-router@6.0.0"]
01:20:31 -- installing ["koa@2","koa-router@6.0.0"]
01:20:38 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:20:39 -- required packages ["koa@2","koa-router@5.2.3"]
01:20:39 -- installing ["koa@2","koa-router@5.2.3"]
01:20:46 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:20:46 Sun, 12 Aug 2018 01:20:46 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at test/instrumentation/modules/koa-router/index.js:82:6
01:20:46 Sun, 12 Aug 2018 01:20:46 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at test/instrumentation/modules/koa-router/index.js:83:6
01:20:46 -- required packages ["koa@2","koa-router@5.2.2"]
01:20:46 -- installing ["koa@2","koa-router@5.2.2"]
01:20:54 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:20:54 Sun, 12 Aug 2018 01:20:54 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at test/instrumentation/modules/koa-router/index.js:82:6
01:20:54 Sun, 12 Aug 2018 01:20:54 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at test/instrumentation/modules/koa-router/index.js:83:6
01:20:54 -- required packages ["koa@2","koa-router@5.2.1"]
01:20:54 -- installing ["koa@2","koa-router@5.2.1"]
01:21:01 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:21:02 Sun, 12 Aug 2018 01:21:02 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at test/instrumentation/modules/koa-router/index.js:82:6
01:21:02 Sun, 12 Aug 2018 01:21:02 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at test/instrumentation/modules/koa-router/index.js:83:6
01:21:02 -- required packages ["koa@2","koa-router@5.2.0"]
01:21:02 -- installing ["koa@2","koa-router@5.2.0"]
01:21:09 -- running test "node test/instrumentation/modules/koa-router/index.js" with koa-router
01:21:09 Sun, 12 Aug 2018 01:21:09 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at test/instrumentation/modules/koa-router/index.js:82:6
01:21:09 Sun, 12 Aug 2018 01:21:09 GMT koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md at test/instrumentation/modules/koa-router/index.js:83:6
01:21:09 -- required packages ["mongodb-core@2.1.20"]
01:21:09 -- installing ["mongodb-core@2.1.20"]
01:21:16 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:21:16 -- required packages ["mongodb-core@3.0.11"]
01:21:16 -- installing ["mongodb-core@3.0.11"]
01:21:23 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:21:23 -- required packages ["mongodb-core@3.1.0"]
01:21:23 -- installing ["mongodb-core@3.1.0"]
01:21:30 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:21:31 -- required packages ["mongodb-core@3.0.9"]
01:21:31 -- installing ["mongodb-core@3.0.9"]
01:21:37 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:21:38 -- required packages ["mongodb-core@3.0.8"]
01:21:38 -- installing ["mongodb-core@3.0.8"]
01:21:44 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:21:44 -- required packages ["mongodb-core@3.0.7"]
01:21:44 -- installing ["mongodb-core@3.0.7"]
01:21:50 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:21:51 -- required packages ["mongodb-core@3.0.6"]
01:21:51 -- installing ["mongodb-core@3.0.6"]
01:21:57 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:21:57 -- required packages ["mongodb-core@3.0.5"]
01:21:57 -- installing ["mongodb-core@3.0.5"]
01:22:04 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:22:04 -- required packages ["mongodb-core@3.0.4"]
01:22:04 -- installing ["mongodb-core@3.0.4"]
01:22:10 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:22:11 -- required packages ["mongodb-core@2.1.19"]
01:22:11 -- installing ["mongodb-core@2.1.19"]
01:22:17 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:22:17 -- required packages ["mongodb-core@3.0.3"]
01:22:17 -- installing ["mongodb-core@3.0.3"]
01:22:23 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:22:24 -- required packages ["mongodb-core@3.0.2"]
01:22:24 -- installing ["mongodb-core@3.0.2"]
01:22:30 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:22:30 -- required packages ["mongodb-core@2.1.18"]
01:22:30 -- installing ["mongodb-core@2.1.18"]
01:22:36 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:22:37 -- required packages ["mongodb-core@3.0.1"]
01:22:37 -- installing ["mongodb-core@3.0.1"]
01:22:43 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:22:43 -- required packages ["mongodb-core@3.0.0"]
01:22:43 -- installing ["mongodb-core@3.0.0"]
01:22:49 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:22:50 -- required packages ["mongodb-core@2.1.17"]
01:22:50 -- installing ["mongodb-core@2.1.17"]
01:22:56 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:22:56 -- required packages ["mongodb-core@2.1.16"]
01:22:56 -- installing ["mongodb-core@2.1.16"]
01:23:03 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:23:03 -- required packages ["mongodb-core@2.1.15"]
01:23:03 -- installing ["mongodb-core@2.1.15"]
01:23:09 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:23:09 -- required packages ["mongodb-core@2.1.14"]
01:23:09 -- installing ["mongodb-core@2.1.14"]
01:23:15 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:23:16 -- required packages ["mongodb-core@2.1.13"]
01:23:16 -- installing ["mongodb-core@2.1.13"]
01:23:22 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:23:22 -- required packages ["mongodb-core@2.1.12"]
01:23:22 -- installing ["mongodb-core@2.1.12"]
01:23:28 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:23:29 -- required packages ["mongodb-core@2.1.11"]
01:23:29 -- installing ["mongodb-core@2.1.11"]
01:23:35 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:23:35 -- required packages ["mongodb-core@2.1.10"]
01:23:35 -- installing ["mongodb-core@2.1.10"]
01:23:41 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:23:42 -- required packages ["mongodb-core@2.1.9"]
01:23:42 -- installing ["mongodb-core@2.1.9"]
01:23:48 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:23:48 -- required packages ["mongodb-core@2.1.8"]
01:23:48 -- installing ["mongodb-core@2.1.8"]
01:23:54 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:23:54 -- required packages ["mongodb-core@2.1.7"]
01:23:54 -- installing ["mongodb-core@2.1.7"]
01:24:01 -- running test "node test/instrumentation/modules/mongodb-core.js" with mongodb-core
01:24:02 Aborted (core dumped)
01:24:02 -- detected failing command, flushing stdout...
01:24:02 TAP version 13
01:24:02 # instrument simple command
01:24:02 
01:24:02 -- fatal: Test exited with code 134
01:24:02 npm ERR! code ELIFECYCLE
01:24:02 npm ERR! errno 134
01:24:02 npm ERR! elastic-apm-node@1.10.2 test-tav: `tav --quiet`
01:24:02 npm ERR! Exit status 134
01:24:02 npm ERR! 
01:24:02 npm ERR! Failed at the elastic-apm-node@1.10.2 test-tav script.
01:24:02 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
01:24:02 
01:24:02 npm ERR! A complete log of this run can be found in:
01:24:02 npm ERR!     /home/node/.npm/_logs/2018-08-12T01_24_02_016Z-debug.log
01:24:02 runbld>>> <<<<<<<<<<<< SCRIPT EXECUTION END <<<<<<<<<<<<
01:24:02 runbld>>> DURATION: 649466ms
01:24:02 runbld>>> STDOUT: 14067 bytes
01:24:02 runbld>>> STDERR: 6447 bytes
01:24:02 runbld>>> WRAPPED PROCESS: FAILURE (134)
01:24:02 runbld>>> Searching for build metadata in /var/lib/jenkins/workspace/elastic+apm-agent-nodejs+master+periodic-tav-tests/NODEJS_VERSION/9/TAV/generic-pool+mysql+mysql2+redis+koa-router+handlebars+mongodb-core/label/linux
01:24:03 runbld>>> Storing build metadata: 
01:24:04 runbld>>> BUILD: https://c150076387b5421f9154dfbf536e5c60.us-west1.gcp.cloud.es.io:9243/build-1463180427010/t/20180812011310-277AE0DB
01:24:05 runbld>>> MAILING: build-apm+agent-nodejs@e***.co
01:24:07 runbld>>> Mail sent.  Output: {:code 0, :error :SUCCESS, :message "messages sent"}
01:24:07 
01:24:12 Build step 'Execute shell' marked build as failure
01:24:12 Sending e-mails to: infra-root+build@elastic.co
01:24:14 Finished: FAILURE
```

</details>
