### ISSUE TITLE
Flush on hapi server stop

### ISSUE THREAD

**Issue by AdriVanHoudt** [elastic/apm-agent-nodejs#361] opened 2018-05-16 14:29 UTC
**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
flush the queue when `server.stop` is called

**Describe alternatives you've considered**
Doing it manually

**Additional context**
I think this just makes sense.
If my process manager sends a SIGINT to the process I manually stop the server with a timeout to let requests finish.
It would make sense (to me) that the agent also flushes the remaining queue at that moment so the least amount of data gets lost.

**Comment by watson** [comment] 2018-05-16 15:51
@AdriVanHoudt would you consider this issue a duplicate of #174 or is it separate because `server.stop` covers a different use-case than when the process exits?

**Comment by AdriVanHoudt** [comment] 2018-05-17 07:52
For me it would be basically the same. I do a server.stop in SIGINT and then call process.exit myself so where in those steps apm flushes does not really matter to me.
I ended up doing 
```js
                server.ext({
                    type: 'onPostStop',
                    method: (srv, next) => {

                        return apm.flush(() => {

                            return next();
                        });
                    }
                });
```
So I'm sure the server has stopped receiving requests.
I think you are more qualified to determine if doing it on process.exit generally or specifically on server.stop for hapi would be a better solution.
I think either works for me.

**Comment by watson** [comment] 2018-05-17 13:49
I'd like to find a general way to implement this functionality that's not specific to hapi only. As you can see in #174, we've been hesitant of automatically flushing the queue on process exit as it most likely will have unforeseen side effects as the agent will hold open the process while performing the flush asynchronously. If the HTTP server is stopped like you do in your case, this shouldn't be a problem, but if not, the server is free to accept new requests which in turn will need to be flushed and so on. So it all gets a bit complicated.

For now I think it's better to do it manually as you found out. When we have a way to do this in a sync manner, we should do it, but until then I think it's better that the user makes an active decision to do so - e.g. by implementing it manually like you're doing.

I'll mark this as a duplicate of #174 and close it for now.

**Closed by watson** 2018-05-17 13:49 UTC
