### ISSUE TITLE
Expand k8s pod ID discovery regex

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-nodejs#1821] opened 2020-09-30 07:58 UTC
Implementing elastic/apm#344

**Comment by astorm** [comment] 2020-10-08 21:11
Thanks for the heads up about the cross agent PR @eyalkoren.  I took a look and it appears the node agent can already handle cgroup paths in the form of 

```
9:freezer:/kubepods.slice/kubepods-pod22949dce_fd8b_11ea_8ede_98f2b32c645c.slice/docker-b15a5bdedd2e7645c3be271364324321b908314e4c77857bbfd32a041148c07f.scope
```

The agent uses the [container-info](https://www.npmjs.com/package/container-info) package parse cgroup paths (this package is maintained by some ~suspicious looking characters~ [familiar faces](https://github.com/Qard/container-info/graphs/contributors)).  I've opened a PR upstream to [add this fixture](https://github.com/Qard/container-info/pull/8) in order to ensure there aren't any future regressions with regards to this. 

Since the agent already supports this functionality, I'm going to close out this issue -- but if there's more to do here please don't hesitate to reopen and let us know.

**Comment by astorm** [comment] 2020-10-09 15:30
@felixbarny @eyalkoren Quick question about [this part of the spec](https://github.com/elastic/apm/pull/344/files#diff-39f0797393af57baa20092add5b9d36e) (that I misread once already)

> The first capturing group in the first case and the second capturing group in the second case is the pod UID. In the latter case, we must unescape underscores (`_`) to hyphens (`-`) in the pod UID.

Is this saying that underscores should always be replaced with dashes in the pod UID? (my interpretation).  Or is it saying that underscores should be replaced with dashes only when the strings match the second regular expression (i.e. the `kubepods.slice` form)

**Comment by eyalkoren** [comment] 2020-10-11 15:33
@astorm It says that underscores should be replaced with dashes only when the strings match the second regular expression.
It would probably make sense to always replace them, but we never encountered those in the first form. As you can see, we are pretty defensive with these regexes with regard to false positives (preferring false negatives).

**Comment by astorm** [comment] 2020-10-30 23:11
@felixbarny @eyalkoren Finally was able to come back around to this.  The following PR landed in the the Node Agent's HTTP client ensures that underscores will always be replaced with dashes in the pod UID.    As previously mentioned, the Node Agent's `container-info` package already parsed paths in the forms captured by the second regular expression.  

This feels done, but if there's additional nuance we're missing here just let us know and we can reopen.

**Comment by trentm** [comment] 2020-11-09 17:38
elastic-apm-http-client@9.4.1 has been released with this.

I'm inclined to bump https://github.com/elastic/apm-agent-nodejs/blob/e9971ef6b91665d8ddbec6c3a740270df179627d/package.json#L85 to `"v9.4.1"` to be explicit about picking up the new version.  Let me know if you object.

**Closed** 2020-11-09 19:32 UTC
Labels: agent-spec
