### ISSUE TITLE
elastic apm does not work with follow-redirects@0.2.0

### ISSUE THREAD

**Issue by kakhaUrigashvili** [elastic/apm-agent-nodejs#2109] opened 2021-06-14 23:01 UTC
One of my dependencies uses follow-redirects@0.2.0 elastic apm will hand request when follow-redirect version 0.2.0 (never version works, but may not able to upgrade).

```
require('elastic-apm-node').start({
    serviceName: 'example-app-local',
    secretToken: '<token>',
    usePathAsTransactionName: true,
    active: true,
    serverUrl:
      '<url>'
  })

const { http } = require('follow-redirects');
// const http = require('http')
const express = require('express')
const app = express()
const port = 3000

const url = 'http://bit.ly/UHfDGO'

app.get('/test', (req, res) => {
  let body = ''
// this will hang
  http.get(url, response => {
    response.on('data', chunk => {
      console.log(chunk.toString())
      body += chunk.toString();
    })
    .on('end', () => {
      console.log('end')
      res.send(body)
    })
  })
  .on('error', err => {
    console.error(err);
  });
  
})

app.listen(port, () => {
  console.log(`example app listening at http://localhost:${port}`)
})
```

**Comment by astorm** [comment] 2021-06-15 01:37
Thanks for reporting @kakhaUrigashvili and for putting together a small reproduction program.  That always helps with these conversations. 

I ran your program with the latest version of the agent and Nodes v8.17.0, v10.24.1, v12.22.1, and v14.16.1, and I didn't see the behavior your described.  In each instance the request finished without issue

```
% curl localhost:3000/test
User-agent: *
Disallow: /lite
Disallow: /html

# No search result pages
Disallow: /*?

# chrome new tab page
Disallow: /chrome_newtab

User-agent: ia_archiver
Disallow: /

Sitemap: https://duckduckgo.com/sitemap.xml
```

In order to help us reproduce this behavior, can you share the exact version of Node.js you're seeing this behavior with? Also, can you share the version of the the agent and express that you're using?  Finally, are there other dependencies in your project that might also be wrapping the request and interfering with things?

If you can provide as much of the above as possible, we'll be able to better proceed.

**Comment by trentm** [comment] 2021-06-15 19:11
@kakhaUrigashvili I admit to be hesitant to support an old 0.2.0 release of follow-redirect. It was released 5 years ago, I believe.

Are you able to mention what the dependency is that uses this old version of follow-redirects? No worry if not.

**Comment by kakhaUrigashvili** [comment] 2021-06-15 20:12
@trentm thank you for the reply. We are able to update the dependency. The issue can be closed.

**Comment by trentm** [comment] 2021-06-15 20:35
Great! Thanks for getting back.

**Comment by msluther** [comment] 2021-06-21 18:35
Can we reopen this please? I'm not super worried about _this_ specific dependency. I'm worried about what this means for the elastic apm library. What is the library doing that caused this to fail and can be sure that it's not going to reproduce with some other library. elastic apm library shouldn't be breaking anything even if its an old library.

**Comment by trentm** [comment] 2021-06-21 19:13
@msluther If this package (elastic-apm-node) was actively **breaking** the behaviour of another node module, then definitely I would agree.

However, my understanding is that this bug report was not about elastic-apm-node breaking follow-redirects@0.2.0, but rather just that when follow-redirects@0.2.0 was used, elastic-apm-node would not trace what it was doing. So tracing functionality was limited, but it didn't actively break the normal functioning of the app. Does that make sense?

**Comment by msluther** [comment] 2021-06-21 19:49
It was actively breaking I believe. 

```js
// this will hang
```

I believe what @kakhaUrigashvili was trying to say is that when elastic-apm was included that the events/response from follow-redirects were never triggered.

**Comment by trentm** [comment] 2021-06-21 23:04
> It was actively breaking I believe.

@msluther That was my bad then. Thanks for correcting me.

**Comment by astorm** [comment] 2021-06-22 00:34
> I'm worried about what this means for the elastic apm library. 

@msluther I was able to reproduce the hanging behavior described in the original issue.  We're happy to reopen this and talk through the issue with you.  In general the guiding principle of all Elastic's APM agents is to _not_ break existing functionality whenever it's possible and reasonable not to.  

Re: _wherever it's possible or reasonable not to_ -- there's often some cases where "what's possible/reasonable" is open to interpretation, and this is one of them. Our approach in these cases is to work with users and customers to make sure they get a solution that works.  Sometimes that's recommending they upgrade to a supported version of a problematic library, and other times that's digging into a issue in order to fix a crasher/hanger.  

The TL;DR; on this one is this seems like a bug that came out of the changes that `follow-redirect` makes the Node's request behavior.  I'm going to give you some background on our agent, and then get into why this is happening with follow redirect.  

## Elastic Agent's HTTP 

Here's what the elastic agent does with regards to outgoing requests.  We monkey patch the `request` and `get` methods of both the `http` and `https` modules.  You can see us monkey patching the methods here

https://github.com/elastic/apm-agent-nodejs/blob/a07eb3a6616d25bf91cb0cf4ce982d7c1af18be4/lib/instrumentation/modules/http.js#L22-L25

https://github.com/elastic/apm-agent-nodejs/blob/a07eb3a6616d25bf91cb0cf4ce982d7c1af18be4/lib/instrumentation/modules/https.js#L23-L27

and here's the code that runs in place of the `request`/`get` methods

https://github.com/elastic/apm-agent-nodejs/blob/a07eb3a6616d25bf91cb0cf4ce982d7c1af18be4/lib/instrumentation/http-shared.js#L131

The basic philosophy of our all wrappers is to 

1. Perform whatever instrumentation we need to do
2. Once done, call the original method with its arguments

We're generally not trying to change the implementation of these methods, we (like most/all APM agents) just need to perform additional actions when methods are called.  

## Follow Redirect at 0.2.0

The `follow-redirects` module (at version 0.0.2) works by returning objects that _extend_ the `http` and `https` modules and redefines how the `get` and `request` methods work.  In v0.2.0 this extending is is done via prototype swapping (this approach is abandoned in later versions).  Unlike the Node.js agent, `follow-redirects` changes the implementation of these methods significantly.  (which isn't intended as a negative critique -- changing the implementation _is_ the point of this module). 

I spent a bit of time debugging their old code, and as best I can tell, when the elastic Node.js Agent is active, the technique that `follow-redirect` uses the create a requestProxy object here doesn't work.  

https://github.com/follow-redirects/follow-redirects/blob/9a13ff409ce5b05463ee0785cb4c048c21800561/create.js#L30-L35
```
		var requestProxy = Object.create(clientRequest);
		requestProxy._events = {};
		requestProxy._eventsCount = 0;
		if (callback) {
			requestProxy.on('response', callback);
		}
```
The `callback` in the above code is the callback registered to handle the request. While it's _registered_ with the `requestProxy` object's `response` event, the `response` event is never invoked. Because it's never invoked, the request hangs.  Looking at this code, it's a little unclear how this could ever work universally -- even with the agent disabled. In fact, if we dig back into the `follow-redirect` repo and look [at this PR](https://github.com/follow-redirects/follow-redirects/pull/44), it appears that this technique has known issues

> The technique used in b4554ff to proxy a request seems to introduce a problem in which connections are not properly closed. This pull requests adds a separate object to act as a proxy of native requests, which as an added benefit brings [abort() should abort the whole chain](https://github.com/follow-redirects/follow-redirects/pull/44)

So, it sounds like under certain circumstances, `follow-redirect@0.2.0` will fail to close the connection.  If the connection never closes, the `response` event never fires and the callbacks never fire.  That sounds like the behavior that was reported in _this issue_.  [The PR fix](https://github.com/follow-redirects/follow-redirects/pull/44) was added to [version 0.3.0 of `follow-redirect`](https://github.com/follow-redirects/follow-redirects/compare/v0.2.0...v0.3.0).  The behavior described in this bug is _not_ present in `follow-redirects@0.3.0`.

So, to sum up again, this seems like an old bug in the `follow-redirect` module that the agent happens to trigger -- not because the agent is doing anything wrong, but because the technique that `follow-redirect@0.2.0` used was unreliable AND `follow-redirect@0.2.0` is also changing the implentation of core Node.js methods.  This would usually be on the authors of `follow-redirect` to fix (which they did!)

Given that this happened in a pre-1.0 module, and that it's also been fixed, and the it was an acknowledged bug in the third party module, and the fix has been available for almost five years, this is probably something we won't address.  

Also, it's not 100% clear what we _could_ do about this case -- the `follow-redirect` modules is failing to close the request. 

What do you think @msluther -- is there more we can/should do in this specific case? It's always tricky when two modules are trying to rewrite the same bit of behavior, but in this case the `follow-redirect@0.2.0` code seems to be the culprit.

**Comment by msluther** [comment] 2021-06-22 17:02
@astorm Thanks for the detailed explanation. I think that alleviates my concerns quite a bit. I was less concerned about this specific case and more worried about systemic problems as we slowly adopt elastic apm. This definitely seems like it was a bug in `follow-redirect` that elastic-apm just exacerbated. Given that, I'm okay with closing out the issue.

Thanks again for the detailed investigation. 😄

**Comment by astorm** [comment] 2021-06-22 20:14
Always happy to help @msluther -- direct customer feedback is what makes the agent better over time.  Good luck rolling the agent out across your projects! Re-closing this one.

**Closed by astorm** 2021-06-22 20:14 UTC
Labels: agent-nodejs
