### ISSUE TITLE
Require time and size unit suffixes

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1504] opened 2019-11-01 14:58 UTC
I just remembered that this probably was forgotten in the 3.0.0 release, so I'm just creating this issue in case you want to remember it for the 4.0.0 release.

The time-based config options `abortedErrorThreshold`, `apiRequestTime`, `metricsInterval`, and `serverTimeout` should require that a suffix is provided when configured (`m`, `s`, or `ms`). Likewise, the size based config options `apiRequestSize` and `errorMessageMaxLength` should require a either `b`, `kb`, `mb`, or `gb`.

**Comment by trentm** [comment] 2022-07-26 23:57
Dupe of https://github.com/elastic/apm-agent-nodejs/issues/2121 (I'm keeping the newer one.)

**Closed by trentm** 2022-07-26 23:57 UTC
Labels: breaking change, agent-nodejs
