### ISSUE TITLE
memory leak problem

### ISSUE THREAD

**Issue by joway** [elastic/apm-agent-nodejs#398] opened 2018-06-15 12:48 UTC
We have add the apm agent with express , our codes is:

```
require('elastic-apm-node').start({
    serviceName: 'activity-service',
    serverUrl: 'http://es-apm-svc.infra.svc.cluster.local:8200',
    transactionSampleRate: 0.2,
    transactionMaxSpans: 32,
    flushInterval: 5,
    serverTimeout: 10,
    maxQueueSize: 50,
})

global.Promise = require('bluebird')

const PORT = process.env.PORT || 7000
const app = require('./app')

app.listen(PORT, function () {
    console.info('Node app is running, port:', PORT)
})
```

But we find the memory usage is increasing until hit the memory limit .

![image](https://user-images.githubusercontent.com/8353464/41465583-52a9cc2e-70d1-11e8-8c97-24489a313ce9.png)

We also put the same code in Koa applications , but the problem is still existed .

We find the issues elastic/apm-agent-nodejs#243 But @Qard said that it has been fixed ? 

We also try to change our config like ：
```
require('elastic-apm-node').start({
    serviceName: 'activity-service',
    serverUrl: 'http://es-apm-svc.infra.svc.cluster.local:8200',
    transactionSampleRate: 0.2,
    transactionMaxSpans: 32,
    flushInterval: 5,
    serverTimeout: 10,
    maxQueueSize: 50,
    sourceLinesErrorAppFrames: 0,
    sourceLinesErrorLibraryFrames: 0,
})
```

But it's not work .

Our dependencies is : 
```
    "mongoose": "4.9.9",
    "express": "4.12.4",
    "bluebird": "3.1.1",
```

and the applications run  in kubernets .

**Comment by watson** [comment] 2018-06-15 13:19
Thanks for reporting this.

I have a few follow up questions to help us get to the bottom of the leak:

- Are you using the latest version of the agent?
- Are you running with any other APM agent loaded at the same time as Elastic APM?
- Do you still see a memory leak if you disable span stack traces using [`captureSpanStackTraces: false`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#capture-span-stack-traces)?

**Comment by joway** [comment] 2018-06-15 13:39
Hi, @watson 

1. we using the latest version (1.6.0) 
2. no , it's the first line above all other code and we don't use any other apm
3. yes , it's still leak then i set  captureSpanStackTraces= false

**Comment by watson** [comment] 2018-06-18 11:46
Thanks for the details. Which version of Node.js are you running and do you mind sharing the entire `dependencies` section from your package.json file with us?

**Comment by joway** [comment] 2018-06-19 14:30
@watson  node10 and node 8.9 

```json
{
 "dependencies": {
    "@types/lodash": "^4.14.106",
    "aws-sdk": "^2.130.0",
    "bluebird": "^3.5.1",
    "cache-manager": "^2.6.0",
    "cache-manager-store-redis": "^0.2.0",
    "config": "^1.26.2",
    "debug": "^2.6.9",
    "deepcopy": "^0.6.3",
    "elastic-apm-node": "^1.6.0",
    "kafka-node": "^2.2.3",
    "kcors": "^2.2.1",
    "koa": "^2.3.0",
    "koa-bodyparser": "^3.2.0",
    "koa-json-body": "^5.3.0",
    "koa-morgan": "^1.0.1",
    "koa-router": "^7.2.1",
    "koa2-newrelic": "^2.2.0",
    "lodash": "^4.17.4",
    "mongoose": "^4.12.1",
    "newrelic": "^1.40.0",
    "pow-mongodb-fixtures": "^0.14.0",
    "raven": "^2.2.1",
    "redis": "^2.8.0",
    "request": "^2.83.0",
    "request-promise": "^4.2.2",
    "sa-sdk-node": "^1.1.1"
  },
  "devDependencies": {
    "ava": "^0.16.0",
    "eslint": "^3.4.0",
    "eslint-config-airbnb-base": "^10.0.1",
    "eslint-plugin-import": "^2.7.0",
    "nock": "^8.0.0",
    "nodemon": "^1.12.1",
    "rewire": "^2.5.2",
    "sinon": "^1.17.5",
    "sinon-as-promised": "^4.0.2",
    "supertest": "^2.0.0"
  },
}
```

**Comment by Thetortuga** [comment] 2018-06-20 08:15
Hello,

We are tracking a memory leak in our code too for a while. After some investigations, it seems that it could come from this agent.
It only appears when we execute external HTTP request with request-promise module.
By analyzing memory dumps, it appears that a lot of "Transaction" instances are still in the memory.

**Comment by watson** [comment] 2018-06-20 10:02
@joway I can see you're running New Relic at the same time as Elastic APM. We have seen situations where running multiple APM agents in the same app will generate memory leaks, and it's as such not something advice doing. Would it be possible for you to disable New Relic for a short time to see if that removes the memory leak?

**Comment by joway** [comment] 2018-06-21 02:54
@watson  I have remove newrelic in my code , but not uninstall it in package.json .

**Comment by joway** [comment] 2018-06-21 03:10
@watson I had remove all newrelic things both in code and package.json , and the problem is still existed .

**Comment by joway** [comment] 2018-06-21 03:16
By the way , does the apm-agent-nodejs will write local files ? We use kubernetes , and when it does not mount volume it will write file in memory .

**Comment by watson** [comment] 2018-06-21 07:15
Ok, thank you so much for helping us debug this problem. It's super hard to reproduce these issues, so it helps a lot. Approximately how many requests per minute do your application get where you see this memory leak?

> By the way , does the apm-agent-nodejs will write local files ? We use kubernetes , and when it does not mount volume it will write file in memory .

No the agent never writes anything to disk. It does use an in-memory queue, but that will be flushed and sent to the APM Server when it reaches a 100 transactions (configurable using [`maxQueueSize`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#max-queue-size)) or after 10 seconds (configurable using [`flushInterval`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#flush-interval)) - whichever happens first.

**Comment by Qard** [comment] 2018-06-22 18:55
I've so far been unable to reproduce this leak with mongoose and bluebird under either express or koa. I also did some testing around request-promise and got nothing from that either. I suspect it's likely related to context loss, but it's impossible to verify without a reproducible test case. The most likely candidates to investigate next I think would be aws-sdk, kafka-node and cache-manager. Can you share a bit about how you are using those? I'm especially interested in aws-sdk, since it contains quite a bit.

**Comment by Thetortuga** [comment] 2018-06-27 06:38
In my case, I am using a custom Transaction to handle some udp traffic. @joway On which kind of Transaction / Span are you experiencing leak ? 
I am trying on my side to reproduce the problem with a miminum code example but so far I can't.
My application is running on a legacy server, outside docker, I am not using nor kafka or aws-sdk. 
As a quick fix, I disabled `http` instrumentation, as it seems to fix the issue.

**Comment by watson** [comment] 2018-06-27 10:01
@Thetortuga Thanks for the details. It might be two different memory leaks that you're experiencing. When you say that the memory leak disappears when you disable `http` instrumentation, how do you do that?

@joway I know it might sound silly, but I just want to make sure that the memory leak you're experiencing is actually related to Elastic APM. Does it disappear if you disable the agent by setting `active: false` in the config?

**Comment by joway** [comment] 2018-06-28 02:52
@watson  yes , it is . And I'm try to create a demo code to reproduce it . https://github.com/joway/elastic-apm-demo

Now , the first thing I found it's that when I enable `source-map-support/register` it will reproduce the memory leak .

But in my production application,  I just use ES5 javascript and no `source-map-support/register` , it also have memory leak .

I doubt that if I have a package which use the `source-map-support/register` ...

**Comment by Thetortuga** [comment] 2018-06-28 05:38
@watson Yes, this is what I begin to suspect. Do you want that I open an new issued about it ?
I disabled http instrumentation with the `disableInstrumentations: ['http']` configuration.

**Comment by mcolmant** [comment] 2018-07-04 07:22
Hi,

We are experiencing the same problem. We have a NodeJS/Express REST API (node 8.11.3) hosted in Heroku.
The memory keeps growing over runtime until to reach the dyno memory limit.
Somehow, it seems that the memory used by the agent is not correctly released.
Once the agent disabled via the environment variable, the memory usage remains very low.

We use the APM agent in version 1.6.0, with default parameters.
Do you think an upgrade can resolve this problem?
What can we do to limit this overhead?

Thanks.

**Comment by Thetortuga** [comment] 2018-07-04 08:14
Finally, I was wrong and the `disableInstrumentations: ['http']` did not succeed to mitigate the leak.
I my case, `captureSpanStackTraces: false` had no effect.
My colleagues replaced me on this issue and are trying the 4 & 5.

**Comment by PestoP** [comment] 2018-07-04 10:19
Hey ! I'm one of the colleagues x)

With 1.8.2 : 

2. Leak
3. Leak
4. No Leak
5. No Leak

We're trying to reproduce with a small environnement, we'll let you know

**Comment by watson** [comment] 2018-07-04 11:20
Thanks @PestoP. Yes it would be super useful for us to have a small app where the problem can be reproduced 👍

**Comment by watson** [comment] 2018-08-28 10:15
@fejalish thanks for reporting this. Is it possible for you to either share an example app where the leak occurs or take some heap snapshots and compare them in the Chrome Developer tools to possibly get an idea of which objects that are leaking?

**Comment by fejalish** [comment] 2018-08-28 10:37
@watson I was going through the heap snapshots to see if I could figure out what was leaking, and saw lots of `Transaction`, `Arrays`, `Objects`, `closures` Constructors, all referencing `IncomingMessage`, `Asynchook`, `_tickCallback()`, and `elasticAPMCallbackWrapper()` objects.

Would you like me to send you the snapshots somehow at all? I have snapshots with and without the leaks.

**Comment by watson** [comment] 2018-08-28 10:57
@fejalish I would not recommend sharing these heap snapshots if they are from a production environment as they might contain personally identifiable information - so an example app would be better. But if you're sure they do not, can you upload them to Dropbox or something similar and share them with me by sending a link to watson at elastic.co?

**Comment by simllll** [comment] 2018-09-05 17:19
Little Offtopic: I had a similar experience with a "memory leak", but for me it was that I have long running transactions, which collect a lot of Spans. So far it looks like setting transactionMaxSpans to e.g. 100 (anything is better than unlimited ;)) solved this for me.

**Comment by Davidiusdadi** [comment] 2018-10-08 10:52
I also ran into this issue in production and setting ```ELASTIC_APM_CAPTURE_SPAN_STACK_TRACES=false``` solved it for now.

Here is how it affacted the memory usage:

![image](https://user-images.githubusercontent.com/1002594/46527603-ff124280-c891-11e8-9691-640431636045.png)

The first drop is an emegency restart due to the memory leak - the second drop is when deployed with ```ELASTIC_APM_CAPTURE_SPAN_STACK_TRACES=false```

I suspect the issue is in apm-agent-nodejs or one of it's dependencies.

Just to give you the full context:
I bootstrap apm-agent-nodejs like you see below in order to solve some local issue where different packages overwrite prepareStackTrace (#588). Im just posting it as the mem-leak might be related to that code (though it's probably not).

The follwoing code allows any library to overwrite prepareStackTrace any way they like while at the same time ensuring that the error-callsites code which is used by apm-agent-nodejs is always executed.
```typescript
type prepTrace = (error, structuredStackTrace) => void
type Wrapper = prepTrace & { impl?: prepTrace }
let prepareStackTraceImpl = undefined
Object.defineProperty(Error, 'prepareStackTrace', {
    set: (v) => {
        if (v.impl) {
             prepareStackTraceImpl = v.impl
            return
        }
        prepareStackTraceImpl = v
    },
    get() {
        if (!prepareStackTraceImpl) {
            return
        }
        const wrapper: Wrapper = (err, callsites) => {
            // the following call is copied from error-callsites package
            Object.defineProperty(err, '__error_callsites', {
                enumerable: false,
                configurable: true,
                writable: false,
                value: callsites
            })

            return wrapper.impl.call(Error, err, callsites)
        }
        wrapper.impl = prepareStackTraceImpl

        return wrapper
    }
})

const apm = require('elastic-apm-node').start()
```

**Comment by junereycasuga** [comment] 2018-10-24 07:17
Is there any fix for this issue yet?

**Comment by Qard** [comment] 2018-10-24 21:17
Unfortunately, no. We haven't yet been able to reproduce the issue ourselves, and no reproduction case has been given.

If you are encountering memory issues like this it would be a huge help to us if you could please share your package.json dependencies, agent settings, Node.js version and, if possible, code for a simplified app that reproduces this issue.

**Comment by TitTurtle** [comment] 2018-11-02 20:41
When using 'async' 'await' functions, it seems to create PROMISE hook type, they don't go into destroy.
This leak memory by storing Transaction inside the Map without releasing it. 
The process keep PROMISE / Promise / PromiseWrap object unless you remove the values in the map using "promiseResolve" callback to delete asyncIds of resolved promise. 
Then the GC can free PROMISE / Promise / PromiseWrap objects (releasing also the Transaction).

**Comment by Qard** [comment] 2018-11-09 00:59
The problem with using `promiseResolve` is that a promise can be listened to with `then(...)` from multiple paths, and clearing the transaction from the map in `promiseResolve` will result in only the first one binding the context correctly.

I'm working on trying to reproduce the issue more consistently in a reduced test case. If we can identify more specifically what interaction leads to this leak so we can hopefully figure out a way to work around it.

It would be nice if we could figure out a way to map async contexts to the current transaction through a weakmap, but async_hooks is based off numeric context ids and weakmaps don't support numeric keys. 🤔 

For now, you can try disabling async_hooks by using `asyncHooks: false` in the config or `ELASTIC_APM_ASYNC_HOOKS=false` in environment variables.

**Comment by swift1911** [comment] 2018-11-12 09:32
is any progress about this issue?

**Comment by watson** [comment] 2018-11-13 10:51
Thanks for being patient with us on this. It's been a complicated process to debug and narrow down the culprit.

But we now think that we have a fix. We just released version 1.14.3 of the agent which fixes the memory leak that we identified. Please try it out and let us know if it also fixed it for you 😃

**Comment by swift1911** [comment] 2018-11-15 04:03
@watson Test in my production env, it seems be fixed :)
![image](https://user-images.githubusercontent.com/9301003/48529516-6928f900-e8ce-11e8-8c4e-1f6e9c8e884a.png)

**Comment by junereycasuga** [comment] 2018-11-15 04:16
yea. it seems to be fixed. we have only tested it in our performance testing environment. hopefully we'll get it to our production environment soon. thanks @watson @Qard

**Comment by watson** [comment] 2018-11-15 07:53
Great to hear!

I'll close this issue for now. If it turns out to persist, please leave a comment here and we'll reopen the issue.

**Closed by watson** 2018-11-15 07:53 UTC
Labels: [zube]: In Progress

**Comment by Thetortuga** [comment] 2018-11-21 12:00
Hi. It appears to be ok for us too ! Thanks !

**Comment by ambika93** [comment] 2019-01-08 08:18
@watson  I'm using 2.0.6 version, I'm facing same issue. I'm using all default configuration.
Node dependency as below:
"aerospike": "3.0.2",
    "async": "^2.6.0",
    "bitset.js": "~4.0.1",
    "body-parser": "^1.14.1",
    "commander": "^2.9.0",
    "ejs": "^2.3.4",
    "express": "~4.9.6",
    "kafka-node": "^2.6.1",
    "lodash": "~3.10.1",
    "moment": "~2.10.6",
    "morgan": "~1.3.2",
    "mysql": "^2.10.2",
    "newrelic": "~1.29.0",
    "node-uuid": "^1.4.7",
    "nodemailer": "0.7.1",
    "on-finished": "~2.3.0",
    "q": "^1.4.1",
    "redis": "^2.4.2",
    "request": "^2.69.0"
I'm using new relic but it is diabled currently.

**Comment by watson** [comment] 2019-01-09 09:44
@ambika93 I believe that what caused this particular issue have been fixed. You might be experiencing another similar issue though. Could I get you to open a new GitHub issue instead so that we don't "spam" the people in this thread while we try to work out what's going on?

**Comment by ambika93** [comment] 2019-01-09 16:08
@watson, Thanks for responding. I've opened a separate thread for the same. https://github.com/elastic/apm-agent-nodejs/issues/772
