### ISSUE TITLE
mongodb.instrument is not a function

### ISSUE THREAD

**Issue by ghost** [elastic/apm-agent-nodejs#2307] opened 2021-08-28 13:42 UTC
**Describe the bug**

```
mongodb.instrument is not a function

38 library frames
node_modules/elastic-apm-node/lib/instrumentation/modules/mongodb.js in module.exports at line 16
[15]
[16]  const listener = mongodb.instrument()
[17]  const activeSpans = new Map()
[18]
```

**Environment (please complete the following information)**

- OS: Linux
- Node.js version: 14.15.4
- APM Server version: 7.9.2
- Agent version: 3.20.0
- Mongoose version: 6.0.2

**How are you starting the agent? (please tick one of the boxes)**
```js
require('elastic-apm-node').start({
  captureBody: 'all',
  logLevel: 'trace',
  active: true,
})
```

**Comment by astorm** [comment] 2021-08-30 15:21
Thanks for the report @nontachai-kor.

This issue was fixed in [#2171](https://github.com/elastic/apm-agent-nodejs/pull/2171), which _should_ [be a part of the 3.20.0](https://github.com/elastic/apm-agent-nodejs/blob/v3.20.0/lib/instrumentation/modules/mongodb.js) agent release.

The error message from above reference line 16

```
mongodb.instrument is not a function
//...
[16]  const listener = mongodb.instrument()
```

This appears to be from the [3.18 (or earlier)](https://github.com/elastic/apm-agent-nodejs/blob/v3.18.0/lib/instrumentation/modules/mongodb.js#L16) release.

@nontachai-kor if you look at your

```
node_modules/elastic-apm-node/package.json
```

file, what version of the agent does it show as installed?

**Comment by anotheri** [comment] 2021-09-21 18:31
confirmed, 
I've updated from `"elastic-apm-node": "^3.1.0",` to `"^3.21.1"` and the issue is gone

**Comment by trentm** [comment] 2023-02-01 23:57
Thanks for getting back, @anotheri

**Closed by trentm** 2023-02-01 23:57 UTC
Labels: agent-nodejs
