### ISSUE TITLE
Allow user a way to know when ended spans have been sent

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#798] opened 2019-01-17 12:55 UTC
This code seems correct:

```js
//...
span.end()
agent.flush(function () {
  console.log('all spans have been sent to the APM Server')
  process.exit()
})
```

But since `span.end()` doesn't write the span to the transport stream synchronously, and since `agent.flush()` only knows about and therefore waits for data that have been written to the transport stream, the callback given to `agent.flush()` will in this case be called before the span have been successfully sent.

It's unfortunately not possible to write the span synchronously to the transport stream as it needs to asynchronously process the stack trace before it can be encoded. So that's not a way to fix this issue.

I see a few possible solutions:

1. Synchronously write a promise to the transport stream instead of the encoded span
  **Cons:** Promises add a significant overhead
1. Maintain a counter of how many spans are in the process of being encoded and wait for this to reach zero before the flush actually begins the normal flush routine
  **Cons:** Adds state which is always something we want to avoid

There are possibly others that I haven't considered

_This issue is created based on this discussion: https://discuss.elastic.co/t/spans-are-sent-after-custom-transaction-is-closed-node-js-apm-agent/164444_

**Comment by Qard** [comment] 2019-04-05 00:20
Rather than using a promise, why not just give it the un-encoded span or transaction objects and have the http client call the `_encode` method itself, if the input object has one? Might also be a good idea to have the http client export a symbol to use as the function name rather than just looking for `_encode`.

**Comment by watson** [comment] 2019-04-09 08:35
It would move the logic of knowing if this encode function is sync or async into the http client module, which is not a really nice API either. We could, of course, require the API to always be async, but that would add an encoding overhead to metrics and transactions which don't need to be async 🤔 

If we somehow could "signal" if this needed to be async or not, we could optimize for the case where no stack trace is collected for spans and hence the `span.encode()` function can be called in a sync manner.

I think if we go down this road, we should make it a kind of duck typing API where the http client module just expects to be passed an object with an `encode` function of some sort. Without any use of symbols or anything like that, as this has to work with 3rd party agents as well.

API proposal:

- An `object` should be given to `sendSpan`, `sendTransaction`, `sendError`, or `sendMetricSet`.
- This `objcet` must have two properties:
  - `sync` - A boolean speicifying if the `encode` function can be called in a sync or an async manner
  - `encode([callback])` - A function that either returns an encoded object (if `sync: true`) or requires a callback which will becalled with the encoded object (if `sync: false`)

**Comment by trentm** [comment] 2021-10-16 00:18
Duplicate of #2294 (tho this one came much later, I was working on it before I noticed this issue).

**Closed by trentm** 2021-10-16 00:18 UTC
Labels: enhancement, agent-nodejs
