### ISSUE TITLE
Request body is logged even with `captureBody: off`

### ISSUE THREAD

**Issue by cuporter** [elastic/apm-agent-nodejs#3961] opened 2024-04-08 17:33 UTC
**Describe the bug**

`http.request.body.original` is always logged, even with `captureBody: off` set.

**To Reproduce**

Steps to reproduce the behavior: 
1. Run the simple express application below with `captureBody: off` in the apm.start config.
2. Note that in APM Transactions -> Metadata the `http.request.body.original` value is present, but should not be
3. Omit the `captureBody` option and note that `http.request.body.original` is still present, but should not be
4. Add `captureBody: all` and note that `http.request.body.original` is present, as expected.

**Expected behavior**

The request body should not be logged by default, and should not be logged if `captureBody: off` is configured.

**Environment (please complete the following information)**

- OS: Linux
- Node.js version: 20.11.0
- APM Server version: 8.9.1
- Agent version: 4.5.0

**How are you starting the agent? (please tick one of the boxes)**

- [X] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

Here is a very basic example program that reproduces the issue:
```
const apm = require('elastic-apm-node').start({
  serverUrl: '<url>',
  secretToken: '<token>',
  serviceName: 'chg-elastic-apm-test', 
  environment: 'local',
  captureBody: 'off'
});
const express = require('express')
const app = express()
app.use(express.json())
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.post('/', (req, res) => {
  res.send('Hello World! Body logging is off')
  apm.flush()
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```

Agent config options: 
<details>
  <summary>environment: local and captureBody: off. Omitting captureBody does not change anything.</summary>

```
  serviceName: 'chg-elastic-apm-test', 
  environment: 'local',
  captureBody: 'off'
```
</details>

`package.json` dependencies:
<details>
  <summary>Click to expand</summary>

```
  "dependencies": {
    "elastic-apm-node": "^4.5.0",
    "express": "^4.19.2"
  }
```
</details>

**Comment by cuporter** [comment] 2024-04-24 17:44
No, actually, we are seeing the full message body.

**Comment by cuporter** [comment] 2024-04-24 19:54
I just restested this using elastic-apm-node 4.5.3 and still see `http.request.body.original` written out. I'm looking at it by choosing a transaction and going to the trace sample "Metadata" tab.

**Comment by cuporter** [comment] 2024-04-24 19:55
Here's a screenshot:
![image](https://github.com/elastic/apm-agent-nodejs/assets/63816159/3c1a8e36-788b-47a8-b305-d4acd471b453)

**Comment by trentm** [comment] 2024-04-24 22:06
@cuporter Okay, curious. I don't see how that can happen in the code yet.

Are you able to get the initial line of log output from the APM agent? It looks something like this:

```
{"log.level":"info","@timestamp":"2024-04-24T21:54:12.604Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","agentVersion":"4.5.2","env":{"pid":61314,"proctitle":"node","os":"darwin 23.4.0","arch":"arm64","host":"peach.local","timezone":"UTC-0700","runtime":"Node.js v18.18.2"},"config":{"captureBody":{"source":"start","value":"off","commonName":"capture_body"},"environment":{"source":"start","value":"local"},"logLevel":{"source":"default","value":"info","commonName":"log_level"},"metricsInterval":{"source":"start","value":0,"sourceValue":"0s"},"serverUrl":{"source":"default","value":"http://127.0.0.1:8200/","commonName":"server_url"},"serviceName":{"source":"start","value":"chg-elastic-apm-test-off","commonName":"service_name"},"serviceVersion":{"source":"default","value":"1.0.0","commonName":"service_version"}},"activationMethod":"require","message":"Elastic APM Node.js Agent v4.5.2"}
``` 

That line should include a section that says what it has decided the `captureBody` value is, e.g. in the above example:

```
"config":{"captureBody":{"source":"start","value":"off","commonName":"capture_body"}
```

This will help verify that `captureBody` is indeed "off".  If not, then we'll have to dig in deeper.

**Comment by trentm** [comment] 2024-04-24 22:10
The next step of debugging, if you are able to make local edits, is to apply this change:

```diff
diff --git a/lib/parsers.js b/lib/parsers.js
index 5f4e40a4..1d0a7976 100644
--- a/lib/parsers.js
+++ b/lib/parsers.js
@@ -100,6 +100,7 @@ function getContextFromRequest(req, conf, type) {
       context.body = body;
     }
   }
+  console.log('XXX getContextFromRequest: haveBody=%s captureBody=%s conf.captureBody=%s context=%o', haveBody, captureBody, conf.captureBody, context)

   // TODO: Tempoary fix for https://github.com/elastic/apm-agent-nodejs/issues/813
   if (context.url && context.url.port) {
```

to "node_modules/elastic-apm-node/lib/parsers.js", restart, and reproduce. Then post here the output of that `console.log`.

**Comment by cuporter** [comment] 2024-04-24 22:13
Here's the first line, which does show captureBody is off:
`{"log.level":"info","@timestamp":"2024-04-24T22:12:24.707Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","agentVersion":"4.5.3","env":{"pid":1197189,"proctitle":"node","os":"linux 5.15.146.1-microsoft-standard-WSL2","arch":"x64","host":"CHG3KWDB24","timezone":"UTC-0600","runtime":"Node.js v20.12.2"},"config":{"captureBody":{"source":"start","value":"off","commonName":"capture_body"},"environment":{"source":"start","value":"local"},"logLevel":{"source":"default","value":"info","commonName":"log_level"},"serverUrl":{"source":"start","value":"https://fcf7eb88e9f14ae9b41faf76a3268a41.apm.us-west-2.aws.cloud.es.io/","commonName":"server_url"},"secretToken":{"source":"start","value":"[REDACTED]","commonName":"secret_token"},"serviceName":{"source":"start","value":"chg-elastic-apm-test","commonName":"service_name"},"serviceVersion":{"source":"default","value":"1.0.0","commonName":"service_version"}},"activationMethod":"require","message":"Elastic APM Node.js Agent v4.5.3"}`

I'm not currently set up for local development but I'll see what I can do.

**Comment by cuporter** [comment] 2024-04-24 22:19
@trentm here is the output you requested:
`XXX getContextFromRequest: haveBody=true captureBody=true conf.captureBody=all context={
  http_version: '1.1',
  method: 'POST',
  url: {
    raw: '/',
    protocol: 'http:',
    hostname: 'localhost',
    port: 3000,
    pathname: '/',
    full: 'http://localhost:3000/'
  },
  headers: {
    'accept-encoding': 'gzip, deflate',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36',
    'sforce-duplicate-rule-header': 'allowSave=true, includeRecordDetails=true, runAsCurrentUser=true',
    'content-type': 'application/json',
    authorization: '[REDACTED]',
    accept: '*/*',
    'postman-token': '[REDACTED]',
    host: 'localhost:3000',
    connection: 'keep-alive',
    'content-length': '835'
  },
  socket: { remote_address: '::1' },
  body: '{"category":"job","specialty":"Family Practice","profession":"Physician","post_date":"2022-05-04 17:00:00","non_persistant":{"additional_info":["Dr. DocVeggie is a very good worker"]},"contact":{"title":"Mr.","first_name":"Jalepeño","last_name":"DocVeggie","email":"heinz3@ucsf.edu","address":"221 B Baker St","city":"Pittsburgh","state":"PA","postal_code":"82952","comments":"Give me a call, lets make something happen.","external_id":"1111cdd9-de6d-4730-bebf-cf70eca6421a"},"job":{"number":"JOB-2710999","title":"Neurology job","permanent":true,"travel":true},"web_tracking":{"source":"PPC_Brand_Microsoft"}}'
}`

**Comment by trentm** [comment] 2024-04-24 22:32
Hrm, that says: `conf.captureBody=all` which is why the body is getting included.
So why is the APM agent's config being changed?

I have a guess that this could be from central-config. The APM agent periodically polls the APM server for changes to its config. A subset of config vars can be changed via central-config -- `captureBody` is one of them.

Are you able to run the APM agent with 'debug'-level logging enabled? You can turn that on via he `ELASTIC_APM_LOG_LEVEL=debug` environment variable or `logLevel: 'debug'` in the `apm.start(...)` options.

Then restart and run for a little while. It should be fairly quick after start, because a fetch of central-config is initiated soon after start, and then approximately every 5 minutes.

If I'm right then we should expect to see a log line from this code:

```js
    agent.logger.debug({ remoteConf }, 'central config received');
```

That that `remoteConf` will include a `capture_body` entry.

**Comment by cuporter** [comment] 2024-04-24 22:42
It looks like you are right. It changed almost immediately after startup:
```
{"log.level":"info","@timestamp":"2024-04-24T22:41:56.666Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","agentVersion":"4.5.3","env":{"pid":1216896,"proctitle":"node","os":"linux 5.15.146.1-microsoft-standard-WSL2","arch":"x64","host":"CHG3KWDB24","timezone":"UTC-0600","runtime":"Node.js v20.12.2"},"config":{"captureBody":{"source":"start","value":"off","commonName":"capture_body"},"environment":{"source":"start","value":"local"},"logLevel":{"source":"start","value":"debug","commonName":"log_level"},"serverUrl":{"source":"start","value":"https://fcf7eb88e9f14ae9b41faf76a3268a41.apm.us-west-2.aws.cloud.es.io/","commonName":"server_url"},"secretToken":{"source":"start","value":"[REDACTED]","commonName":"secret_token"},"serviceName":{"source":"start","value":"chg-elastic-apm-test","commonName":"service_name"},"serviceVersion":{"source":"default","value":"1.0.0","commonName":"service_version"}},"activationMethod":"require","message":"Elastic APM Node.js Agent v4.5.3"}
apm captureBody: off
Example app listening on port 3000
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.680Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"adding Node.js module loader hooks"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.680Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"instrumenting fetch"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.685Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"instrumenting finalhandler@1.2.0 module (enabled=true, isImportMod=false)"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.687Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"instrumenting http@20.12.2 module (enabled=true, isImportMod=false)"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.689Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"shimming http.Server.prototype.emit function"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.689Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"shimming http.ServerResponse.prototype.writeHead function"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.689Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"shimming http.request function"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.689Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"shimming http.get function"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.719Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"instrumenting express@4.19.2 module (enabled=true, isImportMod=false)"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.721Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"shimming express.Router.use function"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.721Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"shimming express.static function"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.721Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"copying property mime from express.static"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.723Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"shimming express.Router.Layer.handle function: query"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.723Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"shimming express.Router.Layer.handle function: expressInit"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.723Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"shimming express.Router.Layer.handle function: jsonParser"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.724Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"shimming express.Router.Layer.handle function: bound dispatch"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.724Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"shimming express.Router.Layer.handle function: bound dispatch"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.831Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"no cloud metadata servers responded"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:56.958Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","event.module":"apmclient","apmServerVersion":"8.9.1","message":"fetched APM Server version"}
{"log.level":"debug","@timestamp":"2024-04-24T22:41:57.002Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","remoteConf":{"capture_body":"all","transaction_max_spans":"500","transaction_sample_rate":"0.5"},"message":"central config received"}
{"log.level":"info","@timestamp":"2024-04-24T22:41:57.002Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"Central config success: updated captureBody: all"}
{"log.level":"info","@timestamp":"2024-04-24T22:41:57.002Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"Central config success: updated transactionMaxSpans: 500"}
{"log.level":"info","@timestamp":"2024-04-24T22:41:57.002Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"Central config success: updated transactionSampleRate: 0.5"}
{"log.level":"info","@timestamp":"2024-04-24T22:41:57.002Z","log.logger":"elastic-apm-node","ecs.version":"8.10.0","message":"Central config success: updated spanStackTraceMinDuration: -1"}
```

**Comment by cuporter** [comment] 2024-04-24 22:44
Based on that it sounds like I just need our platform team to remove that central configuration, is that right?

**Comment by trentm** [comment] 2024-04-24 22:45
Yes, that's right, if that is who has access to the relevant central-config pages in your Kibana instance.

If it is a battle-royale you could completely disable central-config via https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#central-config  ;)

**Comment by cuporter** [comment] 2024-04-24 22:46
Ok. We'll do that. Is this a situation where the app configuration should have taken precedence over the central configuration?

**Comment by trentm** [comment] 2024-04-24 22:47
No, at least not by the APM agent design. https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuring-the-agent.html shows the precedence of config sources.  Central-config always wins -- with the caveats that (a) only a subset of config settings can be set via central config and (b) central-config can be disabled locally.

**Comment by cuporter** [comment] 2024-04-24 22:48
Good to know, thank you so much for your help!

**Comment by trentm** [comment] 2024-04-24 22:48
If it helps, central-config can be customized per service_name and environment.

**Comment by trentm** [comment] 2024-04-24 22:49
You are welcome. I'll close this issue now.

**Closed by trentm** 2024-04-24 22:49 UTC
Labels: community
