### ISSUE TITLE
Not send dynamically configured framework info

### ISSUE THREAD

**Issue by posquit0** [elastic/apm-agent-nodejs#812] opened 2019-01-21 05:10 UTC
**Describe the bug**
When I set `ELASTIC_APM_FRAMEWORK_NAME` and `ELASTIC_APM_FRAMEWORK_VERSION` manually, I can see the framework information in Kibana UI. However, I cannot see the framework information in Kibana UI without manual configuration. (I'm using framework which `elastic-apm-node` hooks to get the framework name and version.)

**To Reproduce**
Just use `elastic-apm-node` with the supported framework without manual framework info configuration.

**Expected behavior**
I can see the framework information in Kibana UI.

**Environment (please complete the following information)**
- OS: OS X
- Node.js version: 10.15.0
- APM Server version: 6.5.4
- Agent version: master
- Framework: koa

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your agent config options
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your dependencies section from package.json
    ```
  </details>

**Comment by watson** [comment] 2019-01-21 12:34
I just released v2.2.0 with your commit for the automatic koa detection. It wasn't included in any previous release. Is that what you mean?

**Comment by posquit0** [comment] 2019-01-21 17:02
No. I meant following current conditions.
- I can see framework information when I configured `ELASTIC_APM_FRAMEWORK_NAME` and `ELASTIC_APM_FRAMEWORK_VERSION` environment variables.
- I cannot see framework information when I use the supported framework. `ex. koa`

With `ELASTIC_APM_LOG_LEVEL=trace`, I can see that `elastic-apm-node` hooked well.
```
adding hook to Node.js module loader
shimming http@10.15.0 module
shimming http.Server.prototype.emit function
shimming http.request function
shimming http.ServerResponse.prototype.writeHead function
shimming koa@2.6.2 module
shimming bluebird@3.5.3 module
```

However, I cannot see the framework information in Kibana APM UI

**Comment by posquit0** [comment] 2019-01-24 02:31
Is there any news for this issue? :)

**Comment by watson** [comment] 2019-01-24 08:47
I see now that this is probably a duplicate of #688.

It's a general issue of that the agent currently expect to have this info available at boot (which happens if set via environment variables), but obviously isn't available if it has to wait for `koa` to be required first.

This bug snug in with v2.0.0 where we optimized the APM Server API and code to not keep sending this data up with each transaction.

We're planning to change how this is implemented so that data like this can be updated on the fly instead of having to be available at boot. It does however require us to refactor the code a little bit first, so I can't say exactly when it will be ready.

I'll close this for now and move the discussion to #688

**Closed by watson** 2019-01-24 08:47 UTC
