### ISSUE TITLE
Metric tests fail randomly on AppVeyor/Windows

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1349] opened 2019-09-16 08:07 UTC
The tests for `system.process.cpu.total.norm.pct` fails randomly on AppVeyor because the percentage number is higher than one. 

Examples:

- https://ci.appveyor.com/project/watson/apm-agent-nodejs/builds/27405083
- https://ci.appveyor.com/project/watson/apm-agent-nodejs/builds/27393497
- https://ci.appveyor.com/project/watson/apm-agent-nodejs/builds/27415085

This is an indication that we have a problem with stats on Windows. This could potentially be an issue with Node.js itself on Windows.

**Comment by Qard** [comment] 2019-09-16 22:07
Windows uses the generic collector, which I think the normal test suite wouldn't use, so it could just be some minor difference between the collectors.

**Comment by watson** [comment] 2019-09-17 06:13
But I still wouldn't expect that the percentage was higher than 100% right?

**Comment by Qard** [comment] 2019-09-17 16:18
I meant there could be a minor logical difference that is _wrong_. The existing test coverage only covers it when running on Windows. 🤷‍♂

**Comment by watson** [comment] 2019-09-17 19:22
Ah yes... I was actually thinking we might want to have a "debug" flag to allow a user to switch implementation in case one of them had a bug on a certain system. This could then also be used for testing.

I actually created the branch [`debug-metrics`](https://github.com/elastic/apm-agent-nodejs/tree/debug-metrics) for this purpose because I wanted to see if this fixed an issue for a specific user (see commit https://github.com/elastic/apm-agent-nodejs/commit/175e52495505a1b0e3a298c71d6e21770de9f7d8)

**Comment by Qard** [comment] 2019-09-25 23:15
Closing as this is a duplicate of #1199.

**Closed by Qard** 2019-09-25 23:15 UTC
