### ISSUE TITLE
Allow service.environment to be set

### ISSUE THREAD

**Issue by dpoetzschke** [elastic/apm-agent-nodejs#712] opened 2018-12-05 13:49 UTC
Currently elastic-apm-node does not support any distinguishing between environments like reference / test / production.
This is useful ie. for application running in Kubernetes.
In the Java version of elastic-apm you can set `-Delastic.apm.environment=reference` so you can seperate apm logfiles in Kibana.
Right now i would have to modify the serviceName to distinguish between our different environment.

One solution could be to allow a new ENV var like `ELASTIC_APM_SERVICE_ENVIRONMENT` to be set that is appended in the service payload.

**Comment by watson** [comment] 2018-12-05 14:44
Duplicate of #88  

The `service.environment` property is unfortunately not fully supported by the UI yet. It was added to the Java agent before the UI was ready, so we retrospectively added a warning to the [Java agent API documentation](https://www.elastic.co/guide/en/apm/agent/java/1.x/config-core.html#config-environment) specifying that you probably shouldn't use it, or at least be aware of UI will behave unexpectedly:

![image](https://user-images.githubusercontent.com/10602/49520428-89cbe980-f8a3-11e8-97c3-0a3ffcb70281.png)

I'll close this issue now, but if you have any other questions regarding `service.environment`, feel free to post them in #88 😃

**Closed by watson** 2018-12-05 14:44 UTC
