### ISSUE TITLE
MariaDB Support

### ISSUE THREAD

**Issue by astorm** [elastic/apm-agent-nodejs#2174] opened 2021-08-03 14:59 UTC
**Is your feature request related to a problem? Please describe.**

We'd like to add support for the [mariadb](https://www.npmjs.com/package/mariadb) package.  

**Describe the solution you'd like**
When using knex with the mariadb driver (or using mariadb stand alone) we'd like DB spans for queries.

**Comment by astorm** [comment] 2021-08-03 15:01
@Nisgrak how familiar are you with our instrumentation packages -- what can we do to help you get started?

**Comment by trentm** [comment] 2023-06-12 21:49
Dupe of https://github.com/elastic/apm-agent-nodejs/issues/1759

**Comment by trentm** [comment] 2024-02-13 19:33
Closing as dupe.

**Closed by trentm** 2024-02-13 19:33 UTC
Labels: agent-nodejs
