### ISSUE TITLE
Change logUncaughtException default to true in v4.0.0

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-nodejs#1433] opened 2019-10-07 07:28 UTC
Revert elastic/apm-agent-nodejs#1432 to ensure `logUncaughtException` is turned on by default in the next major

**Comment by trentm** [comment] 2022-07-26 23:59
Dupe of https://github.com/elastic/apm-agent-nodejs/issues/2412

**Closed by trentm** 2022-07-26 23:59 UTC
Labels: breaking change, agent-nodejs
