### ISSUE TITLE
Agent not working with Yarn Pnp + NextJS

### ISSUE THREAD

**Issue by cmartineauOptimum** [elastic/apm-agent-nodejs#4000] opened 2024-04-30 18:36 UTC
**Describe the bug**

When running the apm agent following the documentation for a nextjs project, using Yarn Berry with Pnp, I get this error : 

Error: Cannot find module 'elastic-apm-node/start-next.js'

![image](https://github.com/elastic/apm-agent-nodejs/assets/147861030/d3527c27-5545-4b57-9809-162bde1541e6)

**To Reproduce**

1. clone this repository and navigate to the nextjs example. 

```
npm install --global yarn
yarn install
yarn set version berry
yarn install
```

2. Make sure you are using pnp by modify this line : `nodeLinker: pnp` in .yarnrc.yml 

```
yarn install
yarn run dev
```

**Expected behavior**

I expected the apm to start.

**Environment (please complete the following information)**

- OS: [e.g. Linux]
- Node.js version: v18.18.0
- APM Server version: v8.12.0
- Agent version: v4.5.3

**How are you starting the agent? (please tick one of the boxes)**

- [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [x] Starting node with `-r elastic-apm-node/start`

**Comment by david-luna** [comment] 2024-05-03 08:29
Hi @cmartineauOptimum,

basically what happens is that `Yarn + pnpm` is adding a custom loader for its cache under the hood. To do soo it sets the environment variable `NODE_OPTIONS` to a certain value.

The getting started guide assumes this var is not set so the npm scripts
```
"dev": "NODE_OPTIONS=--require=elastic-apm-node/start-next.js next dev"
```
overriding its value and making the `yarn + pnpm` loader unavailable. 

You can change the script to append the required value into node options. This is an example
```
"dev": "NODE_OPTIONS=\"$NODE_OPTIONS --require=elastic-apm-node/start\" node next dev"
```

This will maintain reference to the required loaders and append the agent start script at the end.

Cheers!

**Comment by cmartineauOptimum** [comment] 2024-05-03 15:25
Hello @david-luna,

I have tried your suggestion and it did work in this repository with the nextjs example. 

When it came to try it with my project, I had this error : 

Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.

 Source path: /workspace/next
 Not found: /workspace/next

it seem it wasn't able to start next. I change your suggestion to 

`   "dev": "NODE_OPTIONS=\"$NODE_OPTIONS --require=elastic-apm-node/start-next.js\" next dev "`

This seem to be working. do you see any issue with the change I made ?

**Comment by david-luna** [comment] 2024-05-10 09:19
Hi @cmartineauOptimum 

As per your last comment in assume the issue is fixed. Should I proceed to close it?

**Comment by cmartineauOptimum** [comment] 2024-05-23 16:49
Yes, thank you

**Closed** 2024-06-03 18:04 UTC
Labels: community
